CREATE TABLE "Z_ORDERSTEP"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "AD_USER_ID"   NUMBER(10,0),
    "C_ORDER_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DATEACTION" DATE,
    "DESCRIPTION" NVARCHAR2(255),
    "ISACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"         NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_ORDERSTEP_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "Z_ORDERSTEPSTATUS" CHAR(2 BYTE),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1001896" PRIMARY KEY ("Z_ORDERSTEP_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "COMPIERE_IDX" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "COMPIERE_DATA" ;
ALTER TABLE C_Order ADD Z_OrderStepStatus CHAR(2);
ALTER TABLE C_Order ADD Z_MajOrderStatus CHAR(1);