CREATE TABLE "C_ORDERDOWNLOAD"
  (
    "AD_CLIENT_ID"       NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"          NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDERDOWNLOAD_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDER_ID"         NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DOWNLOADURL" NVARCHAR2(120) NOT NULL ENABLE,
    "ISACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "NAME" NVARCHAR2(60) NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"  NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_FILETYPE" CHAR(2 BYTE),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1001793" PRIMARY KEY ("C_ORDER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK1001793_1011231" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;