CREATE TABLE XX_CleanUnPaid (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Amount NUMBER, 
C_Order_ID NUMBER(10), Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
XX_CleanUnPaid_ID NUMBER(10) NOT NULL, CONSTRAINT PK1007487X PRIMARY KEY (XX_CleanUnPaid_ID)); 
ALTER TABLE XX_CleanUnPaid ADD Z_PayGI NUMBER; 