ALTER TABLE C_OrderDownload ADD ChangeType CHAR(5); 
UPDATE AD_FIELD set ISREADONLY = 'Y' where AD_FIELD_ID = 1022907;
UPDATE AD_FIELD set ISSAMELINE = 'N' where AD_FIELD_ID = 1022908;
ALTER TABLE C_Order ADD CopyFileODV CHAR(1); 