//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.ecom_common.xsd._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gs1.shared.shared_common.xsd._3.PartyIdentificationType;
import gs1.shared.shared_common.xsd._3.TradeItemIdentificationType;


/**
 * <p>Java class for CollaborativeTradeItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollaborativeTradeItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tradeItemIdentification" type="{urn:gs1:shared:shared_common:xsd:3}TradeItemIdentificationType"/>
 *         &lt;element name="sellerLocation" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType"/>
 *         &lt;element name="buyerLocation" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollaborativeTradeItemType", propOrder = {
    "tradeItemIdentification",
    "sellerLocation",
    "buyerLocation"
})
public class CollaborativeTradeItemType {

    @XmlElement(required = true)
    protected TradeItemIdentificationType tradeItemIdentification;
    @XmlElement(required = true)
    protected PartyIdentificationType sellerLocation;
    @XmlElement(required = true)
    protected PartyIdentificationType buyerLocation;

    /**
     * Gets the value of the tradeItemIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link TradeItemIdentificationType }
     *     
     */
    public TradeItemIdentificationType getTradeItemIdentification() {
        return tradeItemIdentification;
    }

    /**
     * Sets the value of the tradeItemIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeItemIdentificationType }
     *     
     */
    public void setTradeItemIdentification(TradeItemIdentificationType value) {
        this.tradeItemIdentification = value;
    }

    /**
     * Gets the value of the sellerLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getSellerLocation() {
        return sellerLocation;
    }

    /**
     * Sets the value of the sellerLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setSellerLocation(PartyIdentificationType value) {
        this.sellerLocation = value;
    }

    /**
     * Gets the value of the buyerLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getBuyerLocation() {
        return buyerLocation;
    }

    /**
     * Sets the value of the buyerLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setBuyerLocation(PartyIdentificationType value) {
        this.buyerLocation = value;
    }

}
