//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.ecom_common.xsd._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gs1.shared.shared_common.xsd._3.ConsignmentIdentificationType;
import gs1.shared.shared_common.xsd._3.PartyIdentificationType;


/**
 * <p>Java class for ConsignmentReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsignmentReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="consignmentIdentification" type="{urn:gs1:shared:shared_common:xsd:3}ConsignmentIdentificationType"/>
 *         &lt;element name="consignor" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType" minOccurs="0"/>
 *         &lt;element name="consignee" type="{urn:gs1:shared:shared_common:xsd:3}PartyIdentificationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsignmentReferenceType", propOrder = {
    "consignmentIdentification",
    "consignor",
    "consignee"
})
public class ConsignmentReferenceType {

    @XmlElement(required = true)
    protected ConsignmentIdentificationType consignmentIdentification;
    protected PartyIdentificationType consignor;
    protected PartyIdentificationType consignee;

    /**
     * Gets the value of the consignmentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentIdentificationType }
     *     
     */
    public ConsignmentIdentificationType getConsignmentIdentification() {
        return consignmentIdentification;
    }

    /**
     * Sets the value of the consignmentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentIdentificationType }
     *     
     */
    public void setConsignmentIdentification(ConsignmentIdentificationType value) {
        this.consignmentIdentification = value;
    }

    /**
     * Gets the value of the consignor property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getConsignor() {
        return consignor;
    }

    /**
     * Sets the value of the consignor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setConsignor(PartyIdentificationType value) {
        this.consignor = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentificationType }
     *     
     */
    public PartyIdentificationType getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentificationType }
     *     
     */
    public void setConsignee(PartyIdentificationType value) {
        this.consignee = value;
    }

}
