//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.ecom_common.xsd._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for EcomStringAttributeValuePairListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EcomStringAttributeValuePairListType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="attributeName" use="required" type="{urn:gs1:shared:shared_common:xsd:3}String70Type" />
 *       &lt;attribute name="qualifierCodeName" type="{urn:gs1:shared:shared_common:xsd:3}String70Type" />
 *       &lt;attribute name="qualifierCodeList" type="{urn:gs1:shared:shared_common:xsd:3}String70Type" />
 *       &lt;attribute name="qualifierCodeListVersion" type="{urn:gs1:shared:shared_common:xsd:3}String70Type" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EcomStringAttributeValuePairListType", propOrder = {
    "value"
})
public class EcomStringAttributeValuePairListType {

    @XmlValue
    protected String value;
    @XmlAttribute(required = true)
    protected String attributeName;
    @XmlAttribute
    protected String qualifierCodeName;
    @XmlAttribute
    protected String qualifierCodeList;
    @XmlAttribute
    protected String qualifierCodeListVersion;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the attributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * Sets the value of the attributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeName(String value) {
        this.attributeName = value;
    }

    /**
     * Gets the value of the qualifierCodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierCodeName() {
        return qualifierCodeName;
    }

    /**
     * Sets the value of the qualifierCodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierCodeName(String value) {
        this.qualifierCodeName = value;
    }

    /**
     * Gets the value of the qualifierCodeList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierCodeList() {
        return qualifierCodeList;
    }

    /**
     * Sets the value of the qualifierCodeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierCodeList(String value) {
        this.qualifierCodeList = value;
    }

    /**
     * Gets the value of the qualifierCodeListVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierCodeListVersion() {
        return qualifierCodeListVersion;
    }

    /**
     * Sets the value of the qualifierCodeListVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierCodeListVersion(String value) {
        this.qualifierCodeListVersion = value;
    }

}
