//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.ecom_common.xsd._3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gs1.ecom.ecom_common.xsd._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gs1.ecom.ecom_common.xsd._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SealTypeCodeType }
     * 
     */
    public SealTypeCodeType createSealTypeCodeType() {
        return new SealTypeCodeType();
    }

    /**
     * Create an instance of {@link ItemTypeCodeType }
     * 
     */
    public ItemTypeCodeType createItemTypeCodeType() {
        return new ItemTypeCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsInformationType }
     * 
     */
    public DangerousGoodsInformationType createDangerousGoodsInformationType() {
        return new DangerousGoodsInformationType();
    }

    /**
     * Create an instance of {@link LogisticUnitMeasurementType }
     * 
     */
    public LogisticUnitMeasurementType createLogisticUnitMeasurementType() {
        return new LogisticUnitMeasurementType();
    }

    /**
     * Create an instance of {@link StructureTypeCodeType }
     * 
     */
    public StructureTypeCodeType createStructureTypeCodeType() {
        return new StructureTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticUnitType }
     * 
     */
    public LogisticUnitType createLogisticUnitType() {
        return new LogisticUnitType();
    }

    /**
     * Create an instance of {@link GoodsReceiptReportingCodeType }
     * 
     */
    public GoodsReceiptReportingCodeType createGoodsReceiptReportingCodeType() {
        return new GoodsReceiptReportingCodeType();
    }

    /**
     * Create an instance of {@link PerformanceMeasureTypeCodeType }
     * 
     */
    public PerformanceMeasureTypeCodeType createPerformanceMeasureTypeCodeType() {
        return new PerformanceMeasureTypeCodeType();
    }

    /**
     * Create an instance of {@link QualityControlCodeType }
     * 
     */
    public QualityControlCodeType createQualityControlCodeType() {
        return new QualityControlCodeType();
    }

    /**
     * Create an instance of {@link ShipmentTransportationInformationType }
     * 
     */
    public ShipmentTransportationInformationType createShipmentTransportationInformationType() {
        return new ShipmentTransportationInformationType();
    }

    /**
     * Create an instance of {@link CarrierPickUpDropOffDetailsType }
     * 
     */
    public CarrierPickUpDropOffDetailsType createCarrierPickUpDropOffDetailsType() {
        return new CarrierPickUpDropOffDetailsType();
    }

    /**
     * Create an instance of {@link WarehouseABCClassificationCodeType }
     * 
     */
    public WarehouseABCClassificationCodeType createWarehouseABCClassificationCodeType() {
        return new WarehouseABCClassificationCodeType();
    }

    /**
     * Create an instance of {@link SymbolComponentCodeType }
     * 
     */
    public SymbolComponentCodeType createSymbolComponentCodeType() {
        return new SymbolComponentCodeType();
    }

    /**
     * Create an instance of {@link LogisticServiceReferenceTypeCodeType }
     * 
     */
    public LogisticServiceReferenceTypeCodeType createLogisticServiceReferenceTypeCodeType() {
        return new LogisticServiceReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportPaymentMethodCodeType }
     * 
     */
    public TransportPaymentMethodCodeType createTransportPaymentMethodCodeType() {
        return new TransportPaymentMethodCodeType();
    }

    /**
     * Create an instance of {@link TimePeriodScopeTypeCodeType }
     * 
     */
    public TimePeriodScopeTypeCodeType createTimePeriodScopeTypeCodeType() {
        return new TimePeriodScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalReferenceType }
     * 
     */
    public TransactionalReferenceType createTransactionalReferenceType() {
        return new TransactionalReferenceType();
    }

    /**
     * Create an instance of {@link InventoryDutyFeeTaxStatusType }
     * 
     */
    public InventoryDutyFeeTaxStatusType createInventoryDutyFeeTaxStatusType() {
        return new InventoryDutyFeeTaxStatusType();
    }

    /**
     * Create an instance of {@link AppointmentTimeMeasurementBasisTypeCodeType }
     * 
     */
    public AppointmentTimeMeasurementBasisTypeCodeType createAppointmentTimeMeasurementBasisTypeCodeType() {
        return new AppointmentTimeMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link SettlementHandlingTypeCodeType }
     * 
     */
    public SettlementHandlingTypeCodeType createSettlementHandlingTypeCodeType() {
        return new SettlementHandlingTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportPartyRoleCodeType }
     * 
     */
    public TransportPartyRoleCodeType createTransportPartyRoleCodeType() {
        return new TransportPartyRoleCodeType();
    }

    /**
     * Create an instance of {@link ReceivingConditionCodeType }
     * 
     */
    public ReceivingConditionCodeType createReceivingConditionCodeType() {
        return new ReceivingConditionCodeType();
    }

    /**
     * Create an instance of {@link LegalRegistrationType }
     * 
     */
    public LegalRegistrationType createLegalRegistrationType() {
        return new LegalRegistrationType();
    }

    /**
     * Create an instance of {@link EcomAttributeValuePairListType }
     * 
     */
    public EcomAttributeValuePairListType createEcomAttributeValuePairListType() {
        return new EcomAttributeValuePairListType();
    }

    /**
     * Create an instance of {@link CustomsWarehouseStatusCodeType }
     * 
     */
    public CustomsWarehouseStatusCodeType createCustomsWarehouseStatusCodeType() {
        return new CustomsWarehouseStatusCodeType();
    }

    /**
     * Create an instance of {@link SettlementTypeCodeType }
     * 
     */
    public SettlementTypeCodeType createSettlementTypeCodeType() {
        return new SettlementTypeCodeType();
    }

    /**
     * Create an instance of {@link FinancialAdjustmentReasonCodeType }
     * 
     */
    public FinancialAdjustmentReasonCodeType createFinancialAdjustmentReasonCodeType() {
        return new FinancialAdjustmentReasonCodeType();
    }

    /**
     * Create an instance of {@link IdentityDocumentType }
     * 
     */
    public IdentityDocumentType createIdentityDocumentType() {
        return new IdentityDocumentType();
    }

    /**
     * Create an instance of {@link DutyFeeTaxRegistrationType }
     * 
     */
    public DutyFeeTaxRegistrationType createDutyFeeTaxRegistrationType() {
        return new DutyFeeTaxRegistrationType();
    }

    /**
     * Create an instance of {@link LocationScopeParameterTypeCodeType }
     * 
     */
    public LocationScopeParameterTypeCodeType createLocationScopeParameterTypeCodeType() {
        return new LocationScopeParameterTypeCodeType();
    }

    /**
     * Create an instance of {@link MeasurementTypeCodeType }
     * 
     */
    public MeasurementTypeCodeType createMeasurementTypeCodeType() {
        return new MeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link InventorySubLocationType }
     * 
     */
    public InventorySubLocationType createInventorySubLocationType() {
        return new InventorySubLocationType();
    }

    /**
     * Create an instance of {@link PaymentMethodType }
     * 
     */
    public PaymentMethodType createPaymentMethodType() {
        return new PaymentMethodType();
    }

    /**
     * Create an instance of {@link PaymentFormatCodeType }
     * 
     */
    public PaymentFormatCodeType createPaymentFormatCodeType() {
        return new PaymentFormatCodeType();
    }

    /**
     * Create an instance of {@link PlanBucketSizeCodeType }
     * 
     */
    public PlanBucketSizeCodeType createPlanBucketSizeCodeType() {
        return new PlanBucketSizeCodeType();
    }

    /**
     * Create an instance of {@link QuantitySpecificationType }
     * 
     */
    public QuantitySpecificationType createQuantitySpecificationType() {
        return new QuantitySpecificationType();
    }

    /**
     * Create an instance of {@link InventoryMeasurementBasisTypeCodeType }
     * 
     */
    public InventoryMeasurementBasisTypeCodeType createInventoryMeasurementBasisTypeCodeType() {
        return new InventoryMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link PrintingInstructionCodeType }
     * 
     */
    public PrintingInstructionCodeType createPrintingInstructionCodeType() {
        return new PrintingInstructionCodeType();
    }

    /**
     * Create an instance of {@link StockRequirementTypeCodeType }
     * 
     */
    public StockRequirementTypeCodeType createStockRequirementTypeCodeType() {
        return new StockRequirementTypeCodeType();
    }

    /**
     * Create an instance of {@link RemainingQuantityStatusCodeType }
     * 
     */
    public RemainingQuantityStatusCodeType createRemainingQuantityStatusCodeType() {
        return new RemainingQuantityStatusCodeType();
    }

    /**
     * Create an instance of {@link IdentityDocumentTypeCodeType }
     * 
     */
    public IdentityDocumentTypeCodeType createIdentityDocumentTypeCodeType() {
        return new IdentityDocumentTypeCodeType();
    }

    /**
     * Create an instance of {@link InventoryStatusCodeType }
     * 
     */
    public InventoryStatusCodeType createInventoryStatusCodeType() {
        return new InventoryStatusCodeType();
    }

    /**
     * Create an instance of {@link CarrierTrackAndTraceInformationType }
     * 
     */
    public CarrierTrackAndTraceInformationType createCarrierTrackAndTraceInformationType() {
        return new CarrierTrackAndTraceInformationType();
    }

    /**
     * Create an instance of {@link CargoTypeCodeType }
     * 
     */
    public CargoTypeCodeType createCargoTypeCodeType() {
        return new CargoTypeCodeType();
    }

    /**
     * Create an instance of {@link PassengerInformationType }
     * 
     */
    public PassengerInformationType createPassengerInformationType() {
        return new PassengerInformationType();
    }

    /**
     * Create an instance of {@link LogisticServiceRequirementCodeType }
     * 
     */
    public LogisticServiceRequirementCodeType createLogisticServiceRequirementCodeType() {
        return new LogisticServiceRequirementCodeType();
    }

    /**
     * Create an instance of {@link PassengerCategoryCodeType }
     * 
     */
    public PassengerCategoryCodeType createPassengerCategoryCodeType() {
        return new PassengerCategoryCodeType();
    }

    /**
     * Create an instance of {@link DangerousGoodsRegulationInformationType }
     * 
     */
    public DangerousGoodsRegulationInformationType createDangerousGoodsRegulationInformationType() {
        return new DangerousGoodsRegulationInformationType();
    }

    /**
     * Create an instance of {@link SynchronisationCalculationTypeCodeType }
     * 
     */
    public SynchronisationCalculationTypeCodeType createSynchronisationCalculationTypeCodeType() {
        return new SynchronisationCalculationTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticEventType }
     * 
     */
    public LogisticEventType createLogisticEventType() {
        return new LogisticEventType();
    }

    /**
     * Create an instance of {@link PeriodicityTypeCodeType }
     * 
     */
    public PeriodicityTypeCodeType createPeriodicityTypeCodeType() {
        return new PeriodicityTypeCodeType();
    }

    /**
     * Create an instance of {@link AdministrativeUnitType }
     * 
     */
    public AdministrativeUnitType createAdministrativeUnitType() {
        return new AdministrativeUnitType();
    }

    /**
     * Create an instance of {@link AdministrativeUnitTypeCodeType }
     * 
     */
    public AdministrativeUnitTypeCodeType createAdministrativeUnitTypeCodeType() {
        return new AdministrativeUnitTypeCodeType();
    }

    /**
     * Create an instance of {@link DutyFeeTaxTypeCodeType }
     * 
     */
    public DutyFeeTaxTypeCodeType createDutyFeeTaxTypeCodeType() {
        return new DutyFeeTaxTypeCodeType();
    }

    /**
     * Create an instance of {@link EffectiveDateTypeCodeType }
     * 
     */
    public EffectiveDateTypeCodeType createEffectiveDateTypeCodeType() {
        return new EffectiveDateTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportTrackingLogEventType }
     * 
     */
    public TransportTrackingLogEventType createTransportTrackingLogEventType() {
        return new TransportTrackingLogEventType();
    }

    /**
     * Create an instance of {@link LeviedDutyFeeTaxType }
     * 
     */
    public LeviedDutyFeeTaxType createLeviedDutyFeeTaxType() {
        return new LeviedDutyFeeTaxType();
    }

    /**
     * Create an instance of {@link ForecastPurposeCodeType }
     * 
     */
    public ForecastPurposeCodeType createForecastPurposeCodeType() {
        return new ForecastPurposeCodeType();
    }

    /**
     * Create an instance of {@link DespatchInformationType }
     * 
     */
    public DespatchInformationType createDespatchInformationType() {
        return new DespatchInformationType();
    }

    /**
     * Create an instance of {@link ServiceLevelMeasurementBasisTypeCodeType }
     * 
     */
    public ServiceLevelMeasurementBasisTypeCodeType createServiceLevelMeasurementBasisTypeCodeType() {
        return new ServiceLevelMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link TransactionalPartyInRoleType }
     * 
     */
    public TransactionalPartyInRoleType createTransactionalPartyInRoleType() {
        return new TransactionalPartyInRoleType();
    }

    /**
     * Create an instance of {@link ShipmentReferenceType }
     * 
     */
    public ShipmentReferenceType createShipmentReferenceType() {
        return new ShipmentReferenceType();
    }

    /**
     * Create an instance of {@link DemandEstimationTypeCodeType }
     * 
     */
    public DemandEstimationTypeCodeType createDemandEstimationTypeCodeType() {
        return new DemandEstimationTypeCodeType();
    }

    /**
     * Create an instance of {@link MaterialTypeCodeType }
     * 
     */
    public MaterialTypeCodeType createMaterialTypeCodeType() {
        return new MaterialTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticServiceReferenceType }
     * 
     */
    public LogisticServiceReferenceType createLogisticServiceReferenceType() {
        return new LogisticServiceReferenceType();
    }

    /**
     * Create an instance of {@link SpecialServiceTypeCodeType }
     * 
     */
    public SpecialServiceTypeCodeType createSpecialServiceTypeCodeType() {
        return new SpecialServiceTypeCodeType();
    }

    /**
     * Create an instance of {@link PackagingConditionCodeType }
     * 
     */
    public PackagingConditionCodeType createPackagingConditionCodeType() {
        return new PackagingConditionCodeType();
    }

    /**
     * Create an instance of {@link TransportReferenceTypeCodeType }
     * 
     */
    public TransportReferenceTypeCodeType createTransportReferenceTypeCodeType() {
        return new TransportReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link QuantitySpecificationTypeCodeType }
     * 
     */
    public QuantitySpecificationTypeCodeType createQuantitySpecificationTypeCodeType() {
        return new QuantitySpecificationTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportMeansTypeCodeType }
     * 
     */
    public TransportMeansTypeCodeType createTransportMeansTypeCodeType() {
        return new TransportMeansTypeCodeType();
    }

    /**
     * Create an instance of {@link OperatingHoursType }
     * 
     */
    public OperatingHoursType createOperatingHoursType() {
        return new OperatingHoursType();
    }

    /**
     * Create an instance of {@link LogisticEventTypeCodeType }
     * 
     */
    public LogisticEventTypeCodeType createLogisticEventTypeCodeType() {
        return new LogisticEventTypeCodeType();
    }

    /**
     * Create an instance of {@link ResponseStatusCodeType }
     * 
     */
    public ResponseStatusCodeType createResponseStatusCodeType() {
        return new ResponseStatusCodeType();
    }

    /**
     * Create an instance of {@link InventorySubLocationFunctionCodeType }
     * 
     */
    public InventorySubLocationFunctionCodeType createInventorySubLocationFunctionCodeType() {
        return new InventorySubLocationFunctionCodeType();
    }

    /**
     * Create an instance of {@link TransactionalTradeItemType }
     * 
     */
    public TransactionalTradeItemType createTransactionalTradeItemType() {
        return new TransactionalTradeItemType();
    }

    /**
     * Create an instance of {@link PackageTotalType }
     * 
     */
    public PackageTotalType createPackageTotalType() {
        return new PackageTotalType();
    }

    /**
     * Create an instance of {@link TransportTrackingObservationType }
     * 
     */
    public TransportTrackingObservationType createTransportTrackingObservationType() {
        return new TransportTrackingObservationType();
    }

    /**
     * Create an instance of {@link SealConditionCodeType }
     * 
     */
    public SealConditionCodeType createSealConditionCodeType() {
        return new SealConditionCodeType();
    }

    /**
     * Create an instance of {@link TransportModeCodeType }
     * 
     */
    public TransportModeCodeType createTransportModeCodeType() {
        return new TransportModeCodeType();
    }

    /**
     * Create an instance of {@link PlanCommitmentLevelCodeType }
     * 
     */
    public PlanCommitmentLevelCodeType createPlanCommitmentLevelCodeType() {
        return new PlanCommitmentLevelCodeType();
    }

    /**
     * Create an instance of {@link LogisticLocationType }
     * 
     */
    public LogisticLocationType createLogisticLocationType() {
        return new LogisticLocationType();
    }

    /**
     * Create an instance of {@link PaymentTermsEventCodeType }
     * 
     */
    public PaymentTermsEventCodeType createPaymentTermsEventCodeType() {
        return new PaymentTermsEventCodeType();
    }

    /**
     * Create an instance of {@link ErrorOrWarningCodeType }
     * 
     */
    public ErrorOrWarningCodeType createErrorOrWarningCodeType() {
        return new ErrorOrWarningCodeType();
    }

    /**
     * Create an instance of {@link SpecialOperatingHoursType }
     * 
     */
    public SpecialOperatingHoursType createSpecialOperatingHoursType() {
        return new SpecialOperatingHoursType();
    }

    /**
     * Create an instance of {@link OrderLogisticalInformationType }
     * 
     */
    public OrderLogisticalInformationType createOrderLogisticalInformationType() {
        return new OrderLogisticalInformationType();
    }

    /**
     * Create an instance of {@link SourceReferenceType }
     * 
     */
    public SourceReferenceType createSourceReferenceType() {
        return new SourceReferenceType();
    }

    /**
     * Create an instance of {@link ChildPackageLevelType }
     * 
     */
    public ChildPackageLevelType createChildPackageLevelType() {
        return new ChildPackageLevelType();
    }

    /**
     * Create an instance of {@link TransportStatusType }
     * 
     */
    public TransportStatusType createTransportStatusType() {
        return new TransportStatusType();
    }

    /**
     * Create an instance of {@link DeliveryTermsType }
     * 
     */
    public DeliveryTermsType createDeliveryTermsType() {
        return new DeliveryTermsType();
    }

    /**
     * Create an instance of {@link TransportServiceCategoryCodeType }
     * 
     */
    public TransportServiceCategoryCodeType createTransportServiceCategoryCodeType() {
        return new TransportServiceCategoryCodeType();
    }

    /**
     * Create an instance of {@link HandlingInstructionType }
     * 
     */
    public HandlingInstructionType createHandlingInstructionType() {
        return new HandlingInstructionType();
    }

    /**
     * Create an instance of {@link TransportStatusReasonCodeType }
     * 
     */
    public TransportStatusReasonCodeType createTransportStatusReasonCodeType() {
        return new TransportStatusReasonCodeType();
    }

    /**
     * Create an instance of {@link ServiceLevelBasisTypeCodeType }
     * 
     */
    public ServiceLevelBasisTypeCodeType createServiceLevelBasisTypeCodeType() {
        return new ServiceLevelBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link PackagingMarkingTypeCodeType }
     * 
     */
    public PackagingMarkingTypeCodeType createPackagingMarkingTypeCodeType() {
        return new PackagingMarkingTypeCodeType();
    }

    /**
     * Create an instance of {@link EcomDocumentType }
     * 
     */
    public EcomDocumentType createEcomDocumentType() {
        return new EcomDocumentType();
    }

    /**
     * Create an instance of {@link TransportServiceLevelCodeType }
     * 
     */
    public TransportServiceLevelCodeType createTransportServiceLevelCodeType() {
        return new TransportServiceLevelCodeType();
    }

    /**
     * Create an instance of {@link TransportEquipmentType }
     * 
     */
    public TransportEquipmentType createTransportEquipmentType() {
        return new TransportEquipmentType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link DeliverDateTypeCodeType }
     * 
     */
    public DeliverDateTypeCodeType createDeliverDateTypeCodeType() {
        return new DeliverDateTypeCodeType();
    }

    /**
     * Create an instance of {@link MarginSchemeCodeType }
     * 
     */
    public MarginSchemeCodeType createMarginSchemeCodeType() {
        return new MarginSchemeCodeType();
    }

    /**
     * Create an instance of {@link LineItemActionCodeType }
     * 
     */
    public LineItemActionCodeType createLineItemActionCodeType() {
        return new LineItemActionCodeType();
    }

    /**
     * Create an instance of {@link TransportServiceConditionTypeCodeType }
     * 
     */
    public TransportServiceConditionTypeCodeType createTransportServiceConditionTypeCodeType() {
        return new TransportServiceConditionTypeCodeType();
    }

    /**
     * Create an instance of {@link CreditReasonCodeType }
     * 
     */
    public CreditReasonCodeType createCreditReasonCodeType() {
        return new CreditReasonCodeType();
    }

    /**
     * Create an instance of {@link SalesMeasurementTypeCodeType }
     * 
     */
    public SalesMeasurementTypeCodeType createSalesMeasurementTypeCodeType() {
        return new SalesMeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link HandlingInstructionCodeType }
     * 
     */
    public HandlingInstructionCodeType createHandlingInstructionCodeType() {
        return new HandlingInstructionCodeType();
    }

    /**
     * Create an instance of {@link OutOfStockMeasurementTypeCodeType }
     * 
     */
    public OutOfStockMeasurementTypeCodeType createOutOfStockMeasurementTypeCodeType() {
        return new OutOfStockMeasurementTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportTrackingSensorObservationType }
     * 
     */
    public TransportTrackingSensorObservationType createTransportTrackingSensorObservationType() {
        return new TransportTrackingSensorObservationType();
    }

    /**
     * Create an instance of {@link DeliveryTimeMeasurementBasisTypeCodeType }
     * 
     */
    public DeliveryTimeMeasurementBasisTypeCodeType createDeliveryTimeMeasurementBasisTypeCodeType() {
        return new DeliveryTimeMeasurementBasisTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticServiceType }
     * 
     */
    public LogisticServiceType createLogisticServiceType() {
        return new LogisticServiceType();
    }

    /**
     * Create an instance of {@link OrderLogisticalDateInformationType }
     * 
     */
    public OrderLogisticalDateInformationType createOrderLogisticalDateInformationType() {
        return new OrderLogisticalDateInformationType();
    }

    /**
     * Create an instance of {@link ItemScopeTypeCodeType }
     * 
     */
    public ItemScopeTypeCodeType createItemScopeTypeCodeType() {
        return new ItemScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link LogisticUnitsType }
     * 
     */
    public LogisticUnitsType createLogisticUnitsType() {
        return new LogisticUnitsType();
    }

    /**
     * Create an instance of {@link DataCarrierTypeCodeType }
     * 
     */
    public DataCarrierTypeCodeType createDataCarrierTypeCodeType() {
        return new DataCarrierTypeCodeType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link DangerousGoodsRegulationCodeType }
     * 
     */
    public DangerousGoodsRegulationCodeType createDangerousGoodsRegulationCodeType() {
        return new DangerousGoodsRegulationCodeType();
    }

    /**
     * Create an instance of {@link InventorySubLocationTypeCodeType }
     * 
     */
    public InventorySubLocationTypeCodeType createInventorySubLocationTypeCodeType() {
        return new InventorySubLocationTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportCargoCharacteristicsType }
     * 
     */
    public TransportCargoCharacteristicsType createTransportCargoCharacteristicsType() {
        return new TransportCargoCharacteristicsType();
    }

    /**
     * Create an instance of {@link TransportReferenceType }
     * 
     */
    public TransportReferenceType createTransportReferenceType() {
        return new TransportReferenceType();
    }

    /**
     * Create an instance of {@link TransactionalItemDataType }
     * 
     */
    public TransactionalItemDataType createTransactionalItemDataType() {
        return new TransactionalItemDataType();
    }

    /**
     * Create an instance of {@link PackagingMarkingType }
     * 
     */
    public PackagingMarkingType createPackagingMarkingType() {
        return new PackagingMarkingType();
    }

    /**
     * Create an instance of {@link ForecastTypeCodeType }
     * 
     */
    public ForecastTypeCodeType createForecastTypeCodeType() {
        return new ForecastTypeCodeType();
    }

    /**
     * Create an instance of {@link EcomStringAttributeValuePairListType }
     * 
     */
    public EcomStringAttributeValuePairListType createEcomStringAttributeValuePairListType() {
        return new EcomStringAttributeValuePairListType();
    }

    /**
     * Create an instance of {@link ObservationTypeCodeType }
     * 
     */
    public ObservationTypeCodeType createObservationTypeCodeType() {
        return new ObservationTypeCodeType();
    }

    /**
     * Create an instance of {@link LowerLevelTradeItemType }
     * 
     */
    public LowerLevelTradeItemType createLowerLevelTradeItemType() {
        return new LowerLevelTradeItemType();
    }

    /**
     * Create an instance of {@link TransportMeansType }
     * 
     */
    public TransportMeansType createTransportMeansType() {
        return new TransportMeansType();
    }

    /**
     * Create an instance of {@link InvoiceDocumentReferenceType }
     * 
     */
    public InvoiceDocumentReferenceType createInvoiceDocumentReferenceType() {
        return new InvoiceDocumentReferenceType();
    }

    /**
     * Create an instance of {@link PurchaseConditionsCommitmentTypeCodeType }
     * 
     */
    public PurchaseConditionsCommitmentTypeCodeType createPurchaseConditionsCommitmentTypeCodeType() {
        return new PurchaseConditionsCommitmentTypeCodeType();
    }

    /**
     * Create an instance of {@link PaymentTermsDiscountType }
     * 
     */
    public PaymentTermsDiscountType createPaymentTermsDiscountType() {
        return new PaymentTermsDiscountType();
    }

    /**
     * Create an instance of {@link LegalRegistrationCodeType }
     * 
     */
    public LegalRegistrationCodeType createLegalRegistrationCodeType() {
        return new LegalRegistrationCodeType();
    }

    /**
     * Create an instance of {@link LocationInformationType }
     * 
     */
    public LocationInformationType createLocationInformationType() {
        return new LocationInformationType();
    }

    /**
     * Create an instance of {@link OrderTypeCodeType }
     * 
     */
    public OrderTypeCodeType createOrderTypeCodeType() {
        return new OrderTypeCodeType();
    }

    /**
     * Create an instance of {@link LocationScopeTypeCodeType }
     * 
     */
    public LocationScopeTypeCodeType createLocationScopeTypeCodeType() {
        return new LocationScopeTypeCodeType();
    }

    /**
     * Create an instance of {@link CollaborativeTradeItemType }
     * 
     */
    public CollaborativeTradeItemType createCollaborativeTradeItemType() {
        return new CollaborativeTradeItemType();
    }

    /**
     * Create an instance of {@link InventoryStatusQuantitySpecificationType }
     * 
     */
    public InventoryStatusQuantitySpecificationType createInventoryStatusQuantitySpecificationType() {
        return new InventoryStatusQuantitySpecificationType();
    }

    /**
     * Create an instance of {@link DangerousGoodsAttributeTypeCodeType }
     * 
     */
    public DangerousGoodsAttributeTypeCodeType createDangerousGoodsAttributeTypeCodeType() {
        return new DangerousGoodsAttributeTypeCodeType();
    }

    /**
     * Create an instance of {@link HarmonizedSystemCodeType }
     * 
     */
    public HarmonizedSystemCodeType createHarmonizedSystemCodeType() {
        return new HarmonizedSystemCodeType();
    }

    /**
     * Create an instance of {@link InvoiceTypeCodeType }
     * 
     */
    public InvoiceTypeCodeType createInvoiceTypeCodeType() {
        return new InvoiceTypeCodeType();
    }

    /**
     * Create an instance of {@link TransportSealType }
     * 
     */
    public TransportSealType createTransportSealType() {
        return new TransportSealType();
    }

    /**
     * Create an instance of {@link TransportInstructionStatusReasonCodeType }
     * 
     */
    public TransportInstructionStatusReasonCodeType createTransportInstructionStatusReasonCodeType() {
        return new TransportInstructionStatusReasonCodeType();
    }

    /**
     * Create an instance of {@link InstallmentDueType }
     * 
     */
    public InstallmentDueType createInstallmentDueType() {
        return new InstallmentDueType();
    }

    /**
     * Create an instance of {@link ReturnablePackagingType }
     * 
     */
    public ReturnablePackagingType createReturnablePackagingType() {
        return new ReturnablePackagingType();
    }

    /**
     * Create an instance of {@link AllowanceChargeType }
     * 
     */
    public AllowanceChargeType createAllowanceChargeType() {
        return new AllowanceChargeType();
    }

    /**
     * Create an instance of {@link UnitMeasurementType }
     * 
     */
    public UnitMeasurementType createUnitMeasurementType() {
        return new UnitMeasurementType();
    }

    /**
     * Create an instance of {@link DangerousGoodsAttributeType }
     * 
     */
    public DangerousGoodsAttributeType createDangerousGoodsAttributeType() {
        return new DangerousGoodsAttributeType();
    }

    /**
     * Create an instance of {@link OrderInstructionCodeType }
     * 
     */
    public OrderInstructionCodeType createOrderInstructionCodeType() {
        return new OrderInstructionCodeType();
    }

    /**
     * Create an instance of {@link TradeItemUnitDescriptorCodeType }
     * 
     */
    public TradeItemUnitDescriptorCodeType createTradeItemUnitDescriptorCodeType() {
        return new TradeItemUnitDescriptorCodeType();
    }

    /**
     * Create an instance of {@link TransactionalPartyType }
     * 
     */
    public TransactionalPartyType createTransactionalPartyType() {
        return new TransactionalPartyType();
    }

    /**
     * Create an instance of {@link VarianceReasonCodeType }
     * 
     */
    public VarianceReasonCodeType createVarianceReasonCodeType() {
        return new VarianceReasonCodeType();
    }

    /**
     * Create an instance of {@link UNLocationCodeType }
     * 
     */
    public UNLocationCodeType createUNLocationCodeType() {
        return new UNLocationCodeType();
    }

    /**
     * Create an instance of {@link DeliverDateInformationType }
     * 
     */
    public DeliverDateInformationType createDeliverDateInformationType() {
        return new DeliverDateInformationType();
    }

    /**
     * Create an instance of {@link TransactionalReferenceTypeCodeType }
     * 
     */
    public TransactionalReferenceTypeCodeType createTransactionalReferenceTypeCodeType() {
        return new TransactionalReferenceTypeCodeType();
    }

    /**
     * Create an instance of {@link PaymentTermsType }
     * 
     */
    public PaymentTermsType createPaymentTermsType() {
        return new PaymentTermsType();
    }

    /**
     * Create an instance of {@link TransportStatusConditionCodeType }
     * 
     */
    public TransportStatusConditionCodeType createTransportStatusConditionCodeType() {
        return new TransportStatusConditionCodeType();
    }

    /**
     * Create an instance of {@link InventoryActivityTypeCodeType }
     * 
     */
    public InventoryActivityTypeCodeType createInventoryActivityTypeCodeType() {
        return new InventoryActivityTypeCodeType();
    }

    /**
     * Create an instance of {@link PartyReferenceType }
     * 
     */
    public PartyReferenceType createPartyReferenceType() {
        return new PartyReferenceType();
    }

    /**
     * Create an instance of {@link InventoryMovementTypeCodeType }
     * 
     */
    public InventoryMovementTypeCodeType createInventoryMovementTypeCodeType() {
        return new InventoryMovementTypeCodeType();
    }

    /**
     * Create an instance of {@link ConsignmentReferenceType }
     * 
     */
    public ConsignmentReferenceType createConsignmentReferenceType() {
        return new ConsignmentReferenceType();
    }

    /**
     * Create an instance of {@link PackageLevelCodeType }
     * 
     */
    public PackageLevelCodeType createPackageLevelCodeType() {
        return new PackageLevelCodeType();
    }

    /**
     * Create an instance of {@link FinancialInstitutionInformationType }
     * 
     */
    public FinancialInstitutionInformationType createFinancialInstitutionInformationType() {
        return new FinancialInstitutionInformationType();
    }

    /**
     * Create an instance of {@link PackageTypeCodeType }
     * 
     */
    public PackageTypeCodeType createPackageTypeCodeType() {
        return new PackageTypeCodeType();
    }

    /**
     * Create an instance of {@link DeliveryTypeCodeType }
     * 
     */
    public DeliveryTypeCodeType createDeliveryTypeCodeType() {
        return new DeliveryTypeCodeType();
    }

}
