ALTER TABLE C_Order ADD IsSchedValid CHAR(1) DEFAULT 'N';

CREATE TABLE Z_ORDERPAYMSCHEDULE
  (
    AD_CLIENT_ID NUMBER(10,0) NOT NULL ENABLE,
    AD_ORG_ID    NUMBER(10,0) NOT NULL ENABLE,
    C_INVOICE_ID NUMBER(10,0),
    C_ORDER_ID   NUMBER(10,0) NOT NULL ENABLE,
    CREATED DATE DEFAULT SYSDATE NOT NULL ENABLE,
    CREATEDBY NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    INVOICE   CHAR(1 BYTE),
    ISACTIVE  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    SEQNO     NUMBER DEFAULT 10,
    TOTALAMT  NUMBER,
    UPDATED DATE DEFAULT SYSDATE NOT NULL ENABLE,
    UPDATEDBY              NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    Z_ORDERPAYMSCHEDULE_ID NUMBER(10,0) NOT NULL ENABLE,
    DUEDATE DATE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT PK1001053 PRIMARY KEY (Z_ORDERPAYMSCHEDULE_ID) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE USERS ENABLE,
    CONSTRAINT FK1001053_1006599 FOREIGN KEY (AD_CLIENT_ID) REFERENCES AD_CLIENT (AD_CLIENT_ID) ENABLE
  );


CREATE TABLE Z_ORDERPAYMSCHEDULELINE
  (
    AD_CLIENT_ID NUMBER(10,0) NOT NULL ENABLE,
    AD_ORG_ID    NUMBER(10,0) NOT NULL ENABLE,
    CREATED DATE DEFAULT SYSDATE NOT NULL ENABLE,
    CREATEDBY    NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    C_TAX_ID     NUMBER(10,0),
    DUEAMT       NUMBER,
    ISACTIVE     CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    M_PRODUCT_ID NUMBER(10,0),
    SEQNO        NUMBER DEFAULT 10,
    UPDATED DATE DEFAULT SYSDATE NOT NULL ENABLE,
    UPDATEDBY                  NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    Z_ORDERPAYMSCHEDULE_ID     NUMBER(10,0) NOT NULL ENABLE,
    Z_ORDERPAYMSCHEDULELINE_ID NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT PK1001054 PRIMARY KEY (Z_ORDERPAYMSCHEDULELINE_ID) USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE USERS ENABLE
  );