ALTER TABLE M_PriceList_Version ADD IsAlign CHAR(1) DEFAULT 'N' CHECK (IsAlign IN ('Y','N'));
call syncposdatabase('ALTER TABLE M_PriceList_Version ADD IsAlign CHAR(1) DEFAULT ''N'' CHECK (IsAlign IN (''Y'',''N''))');
ALTER TABLE M_Product ADD AddPriceProduct CHAR(1) DEFAULT 'N';
call syncposdatabase('ALTER TABLE M_Product ADD AddPriceProduct CHAR(1) DEFAULT ''N''');
CREATE TABLE Z_SyncPriceLog (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_PInstance_ID NUMBER, 
Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsUse CHAR(1) DEFAULT 'N' CHECK (IsUse IN ('Y','N')) NOT NULL, 
Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, Z_SyncPriceLog_ID NUMBER(10) NOT NULL, CONSTRAINT PK1006840 PRIMARY KEY (Z_SyncPriceLog_ID)); 
ALTER TABLE Z_SyncPriceLog ADD CONSTRAINT FK1006840_1033086 FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);