ALTER TABLE C_BPartner ADD Z_ApprovedInv CHAR(1) DEFAULT 'Y';
ALTER TABLE C_Invoice ADD Z_CutOffCalc CHAR(1) DEFAULT NULL;
ALTER TABLE C_Invoice ADD Z_ApprovedInv CHAR(1) DEFAULT NULL;
ALTER TABLE C_InvoiceLine ADD Z_CutOffAmt NUMBER DEFAULT 0;
ALTER TABLE C_InvoiceLine ADD Z_LineStatus CHAR(2) DEFAULT NULL;