insert into AD_EntityType (AD_Client_ID, AD_Org_ID, Updated, Created, UpdatedBy, CreatedBy,AD_EntityType_ID,EntityType,name, description ,help, isactive, classpath, modelpackage, modelvalidationclasses, isregistered, version, record_id, processing, createcomponent, documentationtext, requirecompiereversion, requirecomponentversion, summary) 
select 0,0,sysdate, sysdate,0,0,AD_Sequence_NextNo('AD_EntityType'),'A571','118571 - Quick info',
'',
'',
'Y',
'',
'',
'',
'N',
'380',
0,
'N',
'N',
'',
'',
'',
''
 from dual  
where not exists (select 1 from AD_EntityType where EntityType = 'A571' );

update AD_EntityType set Updated = sysdate, UpdatedBy = 0, name = '118571 - Quick info', description = '', help = '', isactive = 'Y', classpath = '', modelpackage = '', modelvalidationclasses = '', isregistered = 'N', version = '380', record_id = 0, processing = 'N', createcomponent = 'N', documentationtext = '', requirecompiereversion = '', requirecomponentversion = '', summary = '' 
where EntityType = 'A571' ;

update AD_EntityType set Updated = sysdate, UpdatedBy = 0, name = '118571 - Quick info', description = '', help = '', isactive = 'Y', classpath = '', modelpackage = '', modelvalidationclasses = '', isregistered = 'N', version = '380', record_id = 0, processing = 'N', createcomponent = 'N', documentationtext = '', requirecompiereversion = '', requirecomponentversion = '', summary = '' 
where EntityType = 'A571' ;



Insert into AD_QUICKINFO (AD_CLIENT_ID,AD_ORG_ID,AD_QUICKINFO_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,ISACTIVE,NAME,UPDATED,UPDATEDBY) values 
('0','0','100',sysdate,'0',null,'A571','Y','Sales Order Header',sysdate,'100');
Insert into AD_QUICKINFO (AD_CLIENT_ID,AD_ORG_ID,AD_QUICKINFO_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,ISACTIVE,NAME,UPDATED,UPDATEDBY) values 
('0','0','101',sysdate,'100',null,'A571','Y','Sales Order Line',sysdate,'100');
Insert into AD_QUICKINFO (AD_CLIENT_ID,AD_ORG_ID,AD_QUICKINFO_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,ISACTIVE,NAME,UPDATED,UPDATEDBY) values 
('0','0','102',sysdate,'100',null,'A571','Y','Purchase Order Header',sysdate,'100');
Insert into AD_QUICKINFO (AD_CLIENT_ID,AD_ORG_ID,AD_QUICKINFO_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,ISACTIVE,NAME,UPDATED,UPDATEDBY) values 
('0','0','103',sysdate,'100',null,'A571','Y','Purchase Order Line',sysdate,'100');
Insert into AD_QUICKINFO (AD_CLIENT_ID,AD_ORG_ID,AD_QUICKINFO_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,ISACTIVE,NAME,UPDATED,UPDATEDBY) values 
('0','0','104',sysdate,'100',null,'A571','Y','RFQ Order Header',sysdate,'100');


Insert into AD_QUICKINFOLINE 
(AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,
	AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,
	WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) 
values ('0',null,'0','117','101','22',null,null,'181',sysdate,'100',
	'Count of Completed and Closed POs for the product','A571','C_Order','Y','Completed/Closed POs ',null,'COUNT(*)',sysdate,'100','DocStatus IN (''CO'',''CL'') AND C_Order.IsSOTrx=''N'' AND C_Order.IsReturnTrx=''N'' AND 
EXISTS (SELECT 1 FROM C_OrderLine ol WHERE  ol.C_Order_ID = C_Order.C_Order_ID 
AND  M_Product_ID=@M_Product_ID@
 )',null,null,'Y');
Insert into AD_QUICKINFOLINE 
(AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,
	AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,
	WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) 
values ('0',null,'0','118','101','22',null,null,'181',sysdate,'100',
	'Count of completed and closed SOs for the product','A571','C_Order','Y','Completed/Closed SOs',null,'COUNT(*)',sysdate,'100','DocStatus IN (''CO'',''CL'') AND C_Order.IsSOTrx=''Y'' AND C_Order.IsReturnTrx=''N'' AND 
EXISTS (SELECT 1 FROM C_OrderLine ol WHERE  ol.C_Order_ID = C_Order.C_Order_ID 
 AND  M_Product_ID=@M_Product_ID@
 )',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0','2375','0','120','104','19',null,null,'315',sysdate,'100',null,'A571','C_RFQ','Y','Last RFQ',null,'MAX(C_RFQ_ID)',sysdate,'100',null,null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','121','104','40',null,null,'315',sysdate,'100','Drill Down to open quotes','A571','C_Rfq','Y','Open Quotes',null,'COUNT(*)',sysdate,'100','IsActive=''Y''',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','122','103','22',null,null,'181',sysdate,'100','Count of Completed and Closed POs for the product','A571','C_Order','Y','Completed/Closed POs',null,'COUNT(*)',sysdate,'100','DocStatus IN (''CO'',''CL'') AND C_Order.IsSOTrx=''N'' AND C_Order.IsReturnTrx=''N'' AND 
EXISTS (SELECT 1 FROM C_OrderLine ol WHERE  ol.C_Order_ID = C_Order.C_Order_ID 
 AND M_Product_ID=@M_Product_ID@
 )',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','123','103','22',null,null,null,sysdate,'100',null,'A571','C_BPartner','Y','Vendors',null,'COUNT(*)',sysdate,'100','C_BPartner_ID IN (SELECT C_BPartner_ID FROM M_Product_PO WHERE M_Product_ID = @M_Product_ID@  AND  IsActive=''Y'' )',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','102','100','17','289',null,null,sysdate,'100','Credit Status','A571','C_BPartner','Y','Credit status',null,'SOCreditStatus',sysdate,'100','C_BPartner_ID=@C_BPartner_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0','558','0','103','100','19',null,null,'143',sysdate,'100','Last Sales Order','A571','C_Order','Y','Last Sales Order',null,'MAX(C_Order_ID)',sysdate,'100','C_BPartner_ID=@C_BPartner_ID@ AND IsSOTrx=''Y'' AND C_Order_ID NOT IN (@C_Order_ID@)',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','104','100','40',null,null,'232',sysdate,'100','Drill down to open requests','A571','R_Request','Y','Open Requests',null,'COUNT(*)',sysdate,'100','C_BPartner_ID=@C_BPartner_ID@ AND R_Status_ID=100',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','105','101','29',null,null,null,sysdate,'100',null,'A571','M_Product','Y','Inventory Available',' ','bomQtyAvailable(M_Product.M_Product_ID,@M_Warehouse_ID@,0)',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','106','101','29',null,null,'139',sysdate,'100',null,'A571','M_Product','Y','Inventory On-Hand',null,'bomQtyOnHand(M_Product.M_Product_ID,@M_Warehouse_ID@,0) ',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','107','101','29',null,null,null,sysdate,'100',null,'A571','M_Product','Y','Inventory On-Order',null,'bomQtyOrdered(M_Product.M_Product_ID,@M_Warehouse_ID@,0) ',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0','558','0','108','102','19',null,null,'181',sysdate,'100',null,'A571','C_Order','Y','Last Purchase Order',null,'MAX(C_Order_ID)',sysdate,'100','C_BPartner_ID=@C_BPartner_ID@ AND IsSOTrx=''N'' AND C_Order_ID NOT IN (@C_Order_ID@)',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','109','103','29',null,null,null,sysdate,'100',null,'A571','M_Product','Y','Inventory Available',null,'bomQtyAvailable(M_Product.M_Product_ID,@M_Warehouse_ID@,0)',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','110','103','29',null,null,'139',sysdate,'100',null,'A571','M_Product','Y','Inventory On-Hand',null,'bomQtyOnHand(M_Product.M_Product_ID,@M_Warehouse_ID@,0) ',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','111','103','29',null,null,null,sysdate,'100',null,'A571','M_Product','Y','Inventory On-Order',null,'bomQtyOrdered(M_Product.M_Product_ID,@M_Warehouse_ID@,0) ',sysdate,'100','M_Product.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','112','101','37',null,null,null,sysdate,'100',null,'A571','C_Invoice i INNER JOIN C_InvoiceLine l ON (i.C_Invoice_ID=l.C_Invoice_ID)','Y','Last Price','ORDER BY i.DateInvoiced DESC','l.PriceActual',sysdate,'100','l.M_Product_ID=@M_Product_ID@',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','113','101','37',null,null,null,sysdate,'100',null,'A571','RV_Cost','Y','Last Cost',null,'CurrentCostPrice',sysdate,'100','M_Product_ID=@M_Product_ID@ AND C_AcctSchema_ID= (SELECT C_AcctSchema1_ID FROM AD_ClientInfo i WHERE i.AD_Client_ID = @AD_Client_ID@)  AND M_CostElement_ID=(SELECT M_CostElement_ID FROM C_AcctSchema A INNER JOIN M_CostElement C ON (A.CostingMethod=C.CostingMethod) WHERE  CostElementType=''M'' AND A.C_AcctSchema_ID = (SELECT C_AcctSchema1_ID FROM AD_ClientInfo i WHERE i.AD_Client_ID = @AD_Client_ID@)  )',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','114','103','37',null,null,null,sysdate,'100',null,'A571','RV_Cost','Y','Last Cost',null,'CurrentCostPrice',sysdate,'100','M_Product_ID=@M_Product_ID@ AND C_AcctSchema_ID= (SELECT C_AcctSchema1_ID FROM AD_ClientInfo i WHERE i.AD_Client_ID = @AD_Client_ID@)  AND M_CostElement_ID=(SELECT M_CostElement_ID FROM C_AcctSchema A INNER JOIN M_CostElement C ON (A.CostingMethod=C.CostingMethod) WHERE  CostElementType=''M'' AND A.C_AcctSchema_ID = (SELECT C_AcctSchema1_ID FROM AD_ClientInfo i WHERE i.AD_Client_ID = @AD_Client_ID@)  )',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','115','102','40',null,null,'181',sysdate,'100','Drill down to Purchase Orders for the Vendor','A571','C_Order','Y','Vendor Summary',null,'COUNT(*)',sysdate,'100','C_BPartner_ID=@C_BPartner_ID@ AND IsSOTrx=''N''',null,null,'Y');
Insert into AD_QUICKINFOLINE (AD_CLIENT_ID,AD_ELEMENT_ID,AD_ORG_ID,AD_QUICKINFOLINE_ID,AD_QUICKINFO_ID,AD_REFERENCE_ID,AD_REFERENCE_VALUE_ID,AD_TAB_ID,AD_WINDOW_ID,CREATED,CREATEDBY,DESCRIPTION,ENTITYTYPE,FROMCLAUSE,ISACTIVE,NAME,OTHERCLAUSE,SELECTCLAUSE,UPDATED,UPDATEDBY,WHERECLAUSE,DISPLAYLOGIC,SEQNO,ISDISPLAYED) values ('0',null,'0','116','101','22',null,null,null,sysdate,'100',null,'A571','C_BPartner','Y','Vendors',null,'COUNT(*)',sysdate,'100','C_BPartner_ID IN (SELECT C_BPartner_ID FROM M_Product_PO WHERE M_Product_ID = @M_Product_ID@  AND IsActive=''Y''  )',null,null,'Y');
