CREATE TABLE Z_S_FAMILLE (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "ISACTIVE"  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"             NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_S_FAMILLE_ID"        NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    "M_PRODUCT_CATEGORY_ID" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    "VALUE" NVARCHAR2(40) DEFAULT NULL NOT NULL ENABLE,
    "NAME" NVARCHAR2(60) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "FKFAMI_KEY" PRIMARY KEY ("Z_S_FAMILLE_ID"),
    CONSTRAINT "FKCLI_FAMI" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES AD_CLIENT ("AD_CLIENT_ID") ENABLE,
    CONSTRAINT "FKORG_FAMI" FOREIGN KEY ("AD_ORG_ID") REFERENCES AD_ORG ("AD_ORG_ID") ENABLE,
    CONSTRAINT "FKPRDC_FAMI" FOREIGN KEY ("M_PRODUCT_CATEGORY_ID") REFERENCES M_PRODUCT_CATEGORY ("M_PRODUCT_CATEGORY_ID") ENABLE
  );