//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.invoice.xsd._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import gs1.ecom.ecom_common.xsd._3.LeviedDutyFeeTaxType;
import gs1.shared.shared_common.xsd._3.AmountType;
import gs1.shared.shared_common.xsd._3.CurrencyCodeType;


/**
 * <p>Java class for InvoiceTotalsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceTotalsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalInvoiceAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType"/>
 *         &lt;element name="baseAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="prepaidAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="prepaidAmountDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="taxAccountingCurrency" type="{urn:gs1:shared:shared_common:xsd:3}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="totalAmountInvoiceAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalAmountLineAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalInvoiceAmountPayable" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalLineAmountExclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalLineAmountInclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalPaymentDiscountBasisAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalTaxAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="totalVATAmount" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="taxSubtotal" type="{urn:gs1:ecom:ecom_common:xsd:3}LeviedDutyFeeTaxType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceTotalsType", propOrder = {
    "totalInvoiceAmount",
    "baseAmount",
    "prepaidAmount",
    "prepaidAmountDate",
    "taxAccountingCurrency",
    "totalAmountInvoiceAllowancesCharges",
    "totalAmountLineAllowancesCharges",
    "totalInvoiceAmountPayable",
    "totalLineAmountExclusiveAllowancesCharges",
    "totalLineAmountInclusiveAllowancesCharges",
    "totalPaymentDiscountBasisAmount",
    "totalTaxAmount",
    "totalVATAmount",
    "taxSubtotal"
})
public class InvoiceTotalsType {

    @XmlElement(required = true)
    protected AmountType totalInvoiceAmount;
    protected AmountType baseAmount;
    protected AmountType prepaidAmount;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prepaidAmountDate;
    protected CurrencyCodeType taxAccountingCurrency;
    protected AmountType totalAmountInvoiceAllowancesCharges;
    protected AmountType totalAmountLineAllowancesCharges;
    protected AmountType totalInvoiceAmountPayable;
    protected AmountType totalLineAmountExclusiveAllowancesCharges;
    protected AmountType totalLineAmountInclusiveAllowancesCharges;
    protected AmountType totalPaymentDiscountBasisAmount;
    protected AmountType totalTaxAmount;
    protected AmountType totalVATAmount;
    protected List<LeviedDutyFeeTaxType> taxSubtotal;

    /**
     * Gets the value of the totalInvoiceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalInvoiceAmount() {
        return totalInvoiceAmount;
    }

    /**
     * Sets the value of the totalInvoiceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalInvoiceAmount(AmountType value) {
        this.totalInvoiceAmount = value;
    }

    /**
     * Gets the value of the baseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getBaseAmount() {
        return baseAmount;
    }

    /**
     * Sets the value of the baseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setBaseAmount(AmountType value) {
        this.baseAmount = value;
    }

    /**
     * Gets the value of the prepaidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getPrepaidAmount() {
        return prepaidAmount;
    }

    /**
     * Sets the value of the prepaidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPrepaidAmount(AmountType value) {
        this.prepaidAmount = value;
    }

    /**
     * Gets the value of the prepaidAmountDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrepaidAmountDate() {
        return prepaidAmountDate;
    }

    /**
     * Sets the value of the prepaidAmountDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrepaidAmountDate(XMLGregorianCalendar value) {
        this.prepaidAmountDate = value;
    }

    /**
     * Gets the value of the taxAccountingCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getTaxAccountingCurrency() {
        return taxAccountingCurrency;
    }

    /**
     * Sets the value of the taxAccountingCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setTaxAccountingCurrency(CurrencyCodeType value) {
        this.taxAccountingCurrency = value;
    }

    /**
     * Gets the value of the totalAmountInvoiceAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalAmountInvoiceAllowancesCharges() {
        return totalAmountInvoiceAllowancesCharges;
    }

    /**
     * Sets the value of the totalAmountInvoiceAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalAmountInvoiceAllowancesCharges(AmountType value) {
        this.totalAmountInvoiceAllowancesCharges = value;
    }

    /**
     * Gets the value of the totalAmountLineAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalAmountLineAllowancesCharges() {
        return totalAmountLineAllowancesCharges;
    }

    /**
     * Sets the value of the totalAmountLineAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalAmountLineAllowancesCharges(AmountType value) {
        this.totalAmountLineAllowancesCharges = value;
    }

    /**
     * Gets the value of the totalInvoiceAmountPayable property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalInvoiceAmountPayable() {
        return totalInvoiceAmountPayable;
    }

    /**
     * Sets the value of the totalInvoiceAmountPayable property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalInvoiceAmountPayable(AmountType value) {
        this.totalInvoiceAmountPayable = value;
    }

    /**
     * Gets the value of the totalLineAmountExclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalLineAmountExclusiveAllowancesCharges() {
        return totalLineAmountExclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the totalLineAmountExclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalLineAmountExclusiveAllowancesCharges(AmountType value) {
        this.totalLineAmountExclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the totalLineAmountInclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalLineAmountInclusiveAllowancesCharges() {
        return totalLineAmountInclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the totalLineAmountInclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalLineAmountInclusiveAllowancesCharges(AmountType value) {
        this.totalLineAmountInclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the totalPaymentDiscountBasisAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalPaymentDiscountBasisAmount() {
        return totalPaymentDiscountBasisAmount;
    }

    /**
     * Sets the value of the totalPaymentDiscountBasisAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalPaymentDiscountBasisAmount(AmountType value) {
        this.totalPaymentDiscountBasisAmount = value;
    }

    /**
     * Gets the value of the totalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalTaxAmount() {
        return totalTaxAmount;
    }

    /**
     * Sets the value of the totalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalTaxAmount(AmountType value) {
        this.totalTaxAmount = value;
    }

    /**
     * Gets the value of the totalVATAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTotalVATAmount() {
        return totalVATAmount;
    }

    /**
     * Sets the value of the totalVATAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalVATAmount(AmountType value) {
        this.totalVATAmount = value;
    }

    /**
     * Gets the value of the taxSubtotal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxSubtotal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxSubtotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeviedDutyFeeTaxType }
     * 
     * 
     */
    public List<LeviedDutyFeeTaxType> getTaxSubtotal() {
        if (taxSubtotal == null) {
            taxSubtotal = new ArrayList<LeviedDutyFeeTaxType>();
        }
        return this.taxSubtotal;
    }

}
