ALTER TABLE Z_OrgPOS ADD DOCTYPE_TRXPLAN_ID NUMBER(10);
ALTER TABLE Z_OrgPOS ADD CONSTRAINT FK1002310_1031894 FOREIGN KEY (DOCTYPE_TRXPLAN_ID) REFERENCES C_DocType (C_DocType_ID);
call syncposdatabase('ALTER TABLE Z_OrgPOS ADD DOCTYPE_TRXPLAN_ID NUMBER(10)');
update Z_OrgPOS set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
--Update Magasin
update Z_OrgPOS@rhisnes set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@ath set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@sav set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@wavre set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@philippeville set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@ciney set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@baileux set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@bouge set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@erpent set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@dinant set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@libramont set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@marche set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@soignies set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@marcinelle set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@lalouviere set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@boussu set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@beauraing set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@malmedy set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@haccourt set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@bastogne set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@aubel set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@huy set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@neupre set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@braderie set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@jumet set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@rocourt set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;
update Z_OrgPOS@boisdevillers set Updated = sysdate, DOCTYPE_TRXPLAN_ID = 1005986;