ALTER TABLE I_PosOrderLine ADD Description NVARCHAR2(2000);
ALTER TABLE C_Order ADD SAV_STATUS NVARCHAR2(3);
ALTER TABLE I_PosOrder ADD SAV_STATUS NVARCHAR2(3);
CREATE TABLE "Z_SAVSTATUS"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDER_ID"   NUMBER(10,0),
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DATEMOUVEMENT" DATE,
    "ISACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "SAV_STATUS" NVARCHAR2(3),
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"      NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_SAVSTATUS_ID" NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000858" PRIMARY KEY ("Z_SAVSTATUS_ID") ,
    CONSTRAINT "FK1000858_1006979" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
