CREATE TABLE "Z_INTERVENTIONS"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DATEFROM" DATE NOT NULL ENABLE,
    "DATETO" DATE NOT NULL ENABLE,
    "DESCRIPTION" NVARCHAR2(100),
    "ISACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "TASKTYPE" CHAR(1 BYTE) DEFAULT 'P' NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"          NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "VENDOR_ID"          NUMBER(10,0) NOT NULL ENABLE,
    "Z_INTERVENTIONS_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDER_ID"         NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "FK1003160_1018419" FOREIGN KEY ("VENDOR_ID") REFERENCES "COMPILOTE"."C_BPARTNER" ("C_BPARTNER_ID") ENABLE,
    CONSTRAINT "FK1003160_1018423" FOREIGN KEY ("C_ORDER_ID") REFERENCES "COMPILOTE"."C_ORDER" ("C_ORDER_ID") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "COMPIERE_DATA" ;
  
  ALTER TABLE C_Order ADD DateTo DATE;
  
  