CREATE TABLE XX_OrderEventLog (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Table_ID NUMBER(10), AD_User_ID NUMBER(10), 
Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
DateAction DATE, EventType CHAR(2), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, 
Record_ID NUMBER, Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
XX_OrderEventLog_ID NUMBER(10) NOT NULL, XX_WSEventLog_ID NUMBER, CONSTRAINT PK1007594 PRIMARY KEY (XX_OrderEventLog_ID)); 
ALTER TABLE C_Order ADD XX_SendEmailEvent CHAR(1); 
ALTER TABLE XX_ORDEREVENTLOG ADD (DESCRIPTION VARCHAR2(255) );
