//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.ecom_common.xsd._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gs1.shared.shared_common.xsd._3.PaymentTimePeriodType;


/**
 * <p>Java class for InstallmentDueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstallmentDueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="percentOfPaymentDue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="paymentTimePeriod" type="{urn:gs1:shared:shared_common:xsd:3}PaymentTimePeriodType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallmentDueType", propOrder = {
    "percentOfPaymentDue",
    "paymentTimePeriod"
})
public class InstallmentDueType {

    protected float percentOfPaymentDue;
    @XmlElement(required = true)
    protected PaymentTimePeriodType paymentTimePeriod;

    /**
     * Gets the value of the percentOfPaymentDue property.
     * 
     */
    public float getPercentOfPaymentDue() {
        return percentOfPaymentDue;
    }

    /**
     * Sets the value of the percentOfPaymentDue property.
     * 
     */
    public void setPercentOfPaymentDue(float value) {
        this.percentOfPaymentDue = value;
    }

    /**
     * Gets the value of the paymentTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTimePeriodType }
     *     
     */
    public PaymentTimePeriodType getPaymentTimePeriod() {
        return paymentTimePeriod;
    }

    /**
     * Sets the value of the paymentTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTimePeriodType }
     *     
     */
    public void setPaymentTimePeriod(PaymentTimePeriodType value) {
        this.paymentTimePeriod = value;
    }

}
