ALTER TABLE AD_Client ADD C_Location_ID NUMBER(10);
ALTER TABLE AD_Client ADD TaxID NVARCHAR2(20);
ALTER TABLE AD_Client ADD Registration NVARCHAR2(30);
ALTER TABLE AD_Client ADD Num_enreg NVARCHAR2(40);
ALTER TABLE AD_Client ADD URL NVARCHAR2(120);