CREATE TABLE XX_BPARTNER_GROUP (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, Description NVARCHAR2(2000), DocumentNo NVARCHAR2(50), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Processing2 CHAR(1), Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, XX_BPARTNER_GROUP_ID NUMBER(10) NOT NULL, XX_LoadBPGroup CHAR(1), CONSTRAINT PK1007591 PRIMARY KEY (XX_BPARTNER_GROUP_ID)); 
ALTER TABLE XX_BPARTNER_GROUP ADD CONSTRAINT FK1007591_1037000X FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org (AD_Org_ID);
CREATE TABLE XX_BPARTNER_GROUP_L (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, BPartnerValue NVARCHAR2(50), C_BP_Group_ID NUMBER(10), C_BPartner_ID NUMBER(10), Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, GroupValue NVARCHAR2(50), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) DEFAULT 'N' CHECK (IsValid IN ('Y','N')) NOT NULL, Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, XX_BPARTNER_GROUP_ID NUMBER(10), XX_BPARTNER_GROUP_L_ID NUMBER(10) NOT NULL, CONSTRAINT PK1007592 PRIMARY KEY (XX_BPARTNER_GROUP_L_ID)); 
ALTER TABLE XX_BPARTNER_GROUP ADD FileName NVARCHAR2(150);





update AD_WINDOW_ACCESS set AD_CLIENT_ID = (Select AD_CLIENT_ID from AD_Role where AD_Role.AD_Role_ID = AD_WINDOW_ACCESS.AD_Role_ID) where AD_CLIENT_ID = 0 and AD_Role_ID<>0;