ALTER TABLE ZSubPaymentRule ADD Z_CashVariance VARCHAR2(22);
ALTER TABLE ZSubPaymentRule ADD CONSTRAINT FK1000126_1021255 FOREIGN KEY (Z_CashVariance) REFERENCES ZSubPaymentRule (ZSubPaymentRule_ID);
