CREATE TABLE XX_InoutPrepare (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, 
Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, DATEEXPED DATE NOT NULL, 
DocumentNo NVARCHAR2(50), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, 
Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Updated DATE DEFAULT SYSDATE NOT NULL, 
UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, XX_CreateShipEggoWindowImpl CHAR(1), XX_Exped CHAR(1), XX_ExpedConfirm CHAR(1), 
XX_FraisA NUMBER, XX_FraisB NUMBER, XX_InoutPrepare_ID NUMBER(10) NOT NULL, XX_NoContainer NVARCHAR2(50), 
XX_Processed CHAR(1) DEFAULT 'N' CHECK (XX_Processed IN ('Y','N')) NOT NULL, 
CONSTRAINT PK1007802 PRIMARY KEY (XX_InoutPrepare_ID)); 
ALTER TABLE XX_InoutPrepare ADD CONSTRAINT FK1007802_1038993 FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);
ALTER TABLE XX_InoutPrepare ADD CONSTRAINT FK1007802_10389931 FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org (AD_Org_ID);
CREATE TABLE XX_InoutPrepareLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, 
C_OrderLine_ID NUMBER(10) NOT NULL, Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, M_InOutConfirm_ID NUMBER(10), 
M_InOutLineConfirm_ID NUMBER(10), M_InOutLine_ID NUMBER(10) NOT NULL, M_InOut_ID NUMBER(10) NOT NULL,
QtyEntered NUMBER, Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
XX_InoutPrepareLine_ID NUMBER(10) NOT NULL, XX_InoutPrepare_ID NUMBER(10) NOT NULL, CONSTRAINT PK1007803 PRIMARY KEY (XX_InoutPrepare_ID));
CREATE INDEX XX_PINOUT_ORDERL ON XX_INOUTPREPARELINE (C_ORDERLINE_ID);
