ALTER TABLE C_OrderLine ADD IsPrepared CHAR(1) DEFAULT 'N' CHECK (IsPrepared IN ('Y','N')) NOT NULL;
ALTER TABLE C_OrderLine ADD PreparedBy VARCHAR2(22);
ALTER TABLE C_OrderLine ADD CONSTRAINT FK260_1012714 FOREIGN KEY (PreparedBy) REFERENCES AD_User (AD_User_ID);