ALTER TABLE AD_User ADD IsInvoiceValidator CHAR(1) DEFAULT 'N' CHECK (IsInvoiceValidator IN ('Y','N')) ENABLE;
ALTER TABLE C_Invoice ADD XX_InvoiceValidator_ID NUMBER(10);
ALTER TABLE C_Invoice ADD CONSTRAINT FKINV_VALID FOREIGN KEY (XX_InvoiceValidator_ID) REFERENCES AD_User (AD_User_ID);
ALTER TABLE C_Invoice ADD XX_ValidateBy_ID NUMBER(10) DEFAULT NULL;
ALTER TABLE C_Invoice ADD CONSTRAINT FKINV_VALIDBY FOREIGN KEY (XX_ValidateBy_ID) REFERENCES AD_User (AD_User_ID);
ALTER TABLE C_Order ADD XX_InvoiceValidator_ID NUMBER(10);
ALTER TABLE C_Order ADD CONSTRAINT FKORD_VALID FOREIGN KEY (XX_InvoiceValidator_ID) REFERENCES AD_User (AD_User_ID);

CREATE OR REPLACE FORCE VIEW RV_InvoiceValidator (C_INVOICE_ID, AD_CLIENT_ID, AD_ORG_ID, UPDATED, UPDATEDBY, CREATED, CREATEDBY, ISACTIVE, XX_InvoiceValidator_ID, DOCUMENTNO, C_BPARTNER_ID, GRANDTOTAL, DOCSTATUS, IsSOTrx) AS 
SELECT C_Invoice_ID, AD_Client_ID, AD_Org_ID, Updated, UpdatedBy,Created, CreatedBy, isActive, XX_InvoiceValidator_ID,
DocumentNo, C_BPartner_ID, GrandTotal, DocStatus, IsSOTrx
FROM C_Invoice
where DOCSTATUS in ('DR') AND XX_InvoiceValidator_ID IS NOT NULL AND IsSOTrx='N';