ALTER TABLE Z_TrxCODA ADD XX_StrdCode NVARCHAR2(3);
ALTER TABLE Z_TrxCODA ADD C_BPartner_ID NUMBER(10);
ALTER TABLE Z_TrxCODA ADD CONSTRAINT FK1000979_1032175 FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner (C_BPartner_ID);
ALTER TABLE Z_TrxCODA ADD XX_CmsAcct_ID NUMBER(10);
ALTER TABLE Z_TrxCODA ADD CONSTRAINT FK1000979_1032178 FOREIGN KEY (XX_CmsAcct_ID) REFERENCES C_Charge (C_Charge_ID);