create table Z_PosVersion(
  "CLIENT_VALUE" NVARCHAR2(20),
  "CREATED" DATE DEFAULT SYSDATE,
  "VERSION" NVARCHAR2(20),
  "SEQNO" NUMBER(10,0)
);
CREATE TABLE Z_LockPOS (Created DATE DEFAULT SYSDATE, I_PosOrder_ID NUMBER(10) NOT NULL, IsSales CHAR(1) DEFAULT 'N' CHECK (IsSales IN ('Y','N')) NOT NULL, POSNumber NVARCHAR2(5) NOT NULL);