CREATE TABLE Z_TypeEcheance_Trl
  (
    AD_Client_ID NUMBER(10) NOT NULL,
    AD_Language  VARCHAR2(5) NOT NULL,
    AD_Org_ID    NUMBER(10) NOT NULL,
    Created DATE DEFAULT SYSDATE NOT NULL,
    CreatedBy    NUMBER(10) DEFAULT 0 NOT NULL,
    IsActive     CHAR(1) DEFAULT 'Y' CHECK (IsActive     IN ('Y','N')) NOT NULL,
    IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL,
    Name NVARCHAR2(60),
    Updated DATE DEFAULT SYSDATE NOT NULL,
    UpdatedBy          NUMBER(10) DEFAULT 0 NOT NULL,
    Z_TypeEcheance_ID NUMBER(10) NOT NULL,
    CONSTRAINT Z_TypeEcheance_TRL_KEY PRIMARY KEY(Z_TypeEcheance_ID,AD_Language) Enable
  );

ALTER TABLE Z_TypeEcheance_Trl ADD CONSTRAINT FKECH1900872_1906934 FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);

ALTER TABLE Z_TypeEcheance_Trl ADD CONSTRAINT FKECH1900872_1906935 FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org (AD_Org_ID);

ALTER TABLE Z_TypeEcheance_Trl ADD CONSTRAINT FKECH1900872_1906943 FOREIGN KEY (AD_Language) REFERENCES AD_Language (AD_Language) ON DELETE CASCADE;

ALTER TABLE Z_TypeEcheance_Trl ADD CONSTRAINT FKECH1900872_1906941 FOREIGN KEY (Z_TypeEcheance_ID) REFERENCES Z_TypeEcheance (Z_TypeEcheance_ID) ON DELETE CASCADE;

UPDATE AD_Column
SET ISTRANSLATED ='Y'
WHERE COLUMNNAME ='Name'
AND AD_TABLE_ID  =
  (SELECT AD_TABLE_ID FROM AD_TABLE WHERE TABLENAME ='Z_TypeEcheance'
  );
