ALTER TABLE M_MovementLine ADD M_Warehouse_ID NUMBER(10); 
ALTER TABLE M_MovementLine ADD CONSTRAINT FK324_1020347 FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse (M_Warehouse_ID);
ALTER TABLE M_MovementLine ADD M_WarehouseTo_ID NUMBER(10); 
ALTER TABLE M_MovementLine ADD CONSTRAINT FK324_1020348 FOREIGN KEY (M_WarehouseTo_ID) REFERENCES M_Warehouse (M_Warehouse_ID);
ALTER TABLE C_Order ADD MajAR CHAR(1) DEFAULT 'N'; 
ALTER TABLE C_Order ADD MAJARVEND CHAR(1) DEFAULT 'N'; 