CREATE TABLE XX_OrgInfoCODA
  (
    AD_Client_ID NUMBER(10) NOT NULL,
    AD_Org_ID    NUMBER(10) NOT NULL,
    Created      DATE DEFAULT SYSDATE NOT NULL,
    CreatedBy    NUMBER(10) DEFAULT 0 NOT NULL,
    Description NVARCHAR2(50),
    IsActive          CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL,
    Updated           DATE DEFAULT SYSDATE NOT NULL,
    UpdatedBy         NUMBER(10) DEFAULT 0 NOT NULL,
    XX_OrgInfoCODA_ID NUMBER(10) NOT NULL,
    XX_Terminal NVARCHAR2(10) NOT NULL,
    CONSTRAINT PK1006450 PRIMARY KEY (XX_OrgInfoCODA_ID)
  ) ;
  
ALTER TABLE XX_OrgInfoCODA ADD CONSTRAINT FK1006450_1032374 FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);
  
ALTER TABLE XX_OrgInfoCODA ADD CONSTRAINT XX_OrgInfoCODA_XX_Terminal UNIQUE (XX_Terminal);
  
  