CREATE TABLE XX_BP_MATCHING (AD_Client_ID NUMBER(10) NOT NULL, 
AD_Org_ID NUMBER(10) NOT NULL, Created DATE DEFAULT SYSDATE NOT NULL, 
CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, DateAcct DATE NOT NULL, Description NVARCHAR2(2000), 
DocumentNo NVARCHAR2(50), GenerateList CHAR(11), IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL,
Processed CHAR(1) DEFAULT 'N' CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1), 
Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
ValidFrom NUMBER DEFAULT 0 NOT NULL, ValidTo NUMBER DEFAULT 0 NOT NULL, 
XX_BP_MATCHING_ID NUMBER(10) NOT NULL, 
CONSTRAINT PK1007588X PRIMARY KEY (XX_BP_MATCHING_ID)); 
CREATE TABLE XX_BP_MATCHING_DET (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, 
C_BPartner_ID NUMBER(10), C_Invoice_ID NUMBER(10), C_Payment_ID NUMBER(10), 
Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, SOLDE NUMBER,
Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
XX_BP_MATCHING_DET_ID NUMBER(10) NOT NULL, XX_BP_MATCHING_ID NUMBER(10),
CONSTRAINT PK1007590X PRIMARY KEY (XX_BP_MATCHING_DET_ID));
ALTER TABLE XX_BP_MATCHING_DET ADD CONSTRAINT FK1007590_1036978X FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);
CREATE TABLE XX_BP_MATCHING_LINE (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL,
C_BPartner_ID NUMBER(10), Created DATE DEFAULT SYSDATE NOT NULL, CreatedBy NUMBER(10) DEFAULT 0 NOT NULL,
IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, SOLDE NUMBER, Updated DATE DEFAULT SYSDATE NOT NULL,
UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, XX_BP_MATCHING_ID NUMBER(10) NOT NULL, XX_BP_MATCHING_LINE_ID NUMBER(10) NOT NULL, 
CONSTRAINT PK1007589X PRIMARY KEY (XX_BP_MATCHING_LINE_ID));
ALTER TABLE XX_BP_MATCHING_LINE ADD CONSTRAINT FK1007589_1036966X FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);
ALTER TABLE XX_BP_MATCHING ADD C_BPartner_ID NUMBER(10); 
ALTER TABLE XX_BP_MATCHING ADD CONSTRAINT FK1007588_1036992X FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner (C_BPartner_ID);
ALTER TABLE XX_BP_MATCHING_DET ADD DocumentNo NVARCHAR2(50); 
ALTER TABLE XX_BP_MATCHING_DET ADD Value NVARCHAR2(50); 
ALTER TABLE XX_BP_MATCHING_LINE ADD Value NVARCHAR2(50);
ALTER TABLE XX_BP_MATCHING_LINE ADD BPName NVARCHAR2(100); 
ALTER TABLE XX_BP_MATCHING_DET ADD BPName NVARCHAR2(100); 
ALTER TABLE XX_BP_MATCHING_LINE ADD C_AllocationHdr_ID NUMBER(10); 
ALTER TABLE XX_BP_MATCHING_LINE ADD CONSTRAINT FK1007589_1036998X FOREIGN KEY (C_AllocationHdr_ID) REFERENCES C_AllocationHdr (C_AllocationHdr_ID);