//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.invoice.xsd._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import gs1.ecom.ecom_common.xsd._3.AllowanceChargeType;
import gs1.ecom.ecom_common.xsd._3.LeviedDutyFeeTaxType;


/**
 * <p>Java class for InvoiceAllowanceChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceAllowanceChargeType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:gs1:ecom:ecom_common:xsd:3}AllowanceChargeType">
 *       &lt;sequence>
 *         &lt;element name="leviedDutyFeeTax" type="{urn:gs1:ecom:ecom_common:xsd:3}LeviedDutyFeeTaxType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceAllowanceChargeType", propOrder = {
    "leviedDutyFeeTax"
})
public class InvoiceAllowanceChargeType
    extends AllowanceChargeType
{

    protected LeviedDutyFeeTaxType leviedDutyFeeTax;

    /**
     * Gets the value of the leviedDutyFeeTax property.
     * 
     * @return
     *     possible object is
     *     {@link LeviedDutyFeeTaxType }
     *     
     */
    public LeviedDutyFeeTaxType getLeviedDutyFeeTax() {
        return leviedDutyFeeTax;
    }

    /**
     * Sets the value of the leviedDutyFeeTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeviedDutyFeeTaxType }
     *     
     */
    public void setLeviedDutyFeeTax(LeviedDutyFeeTaxType value) {
        this.leviedDutyFeeTax = value;
    }

}
