//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 12:21:57 PM CET 
//


package gs1.ecom.invoice.xsd._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gs1.ecom.ecom_common.xsd._3.CreditReasonCodeType;
import gs1.ecom.ecom_common.xsd._3.DespatchInformationType;
import gs1.ecom.ecom_common.xsd._3.EcomDocumentType;
import gs1.ecom.ecom_common.xsd._3.InvoiceTypeCodeType;
import gs1.ecom.ecom_common.xsd._3.PaymentTermsType;
import gs1.ecom.ecom_common.xsd._3.ShipmentTransportationInformationType;
import gs1.ecom.ecom_common.xsd._3.TransactionalPartyType;
import gs1.ext.xmldsig.xsd._3.DigitalSignatureType;
import gs1.shared.shared_common.xsd._3.CountryCodeType;
import gs1.shared.shared_common.xsd._3.CurrencyCodeType;
import gs1.shared.shared_common.xsd._3.CurrencyExchangeRateInformationType;
import gs1.shared.shared_common.xsd._3.DateTimeRangeType;
import gs1.shared.shared_common.xsd._3.Description500Type;
import gs1.shared.shared_common.xsd._3.DocumentReferenceType;
import gs1.shared.shared_common.xsd._3.EntityIdentificationType;


/**
 * <p>Java class for InvoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:gs1:ecom:ecom_common:xsd:3}EcomDocumentType">
 *       &lt;sequence>
 *         &lt;element name="invoiceIdentification" type="{urn:gs1:shared:shared_common:xsd:3}EntityIdentificationType"/>
 *         &lt;element name="digitalSignature" type="{urn:gs1:ext:xmldsig:xsd:3}DigitalSignatureType" minOccurs="0"/>
 *         &lt;element name="invoiceType" type="{urn:gs1:ecom:ecom_common:xsd:3}InvoiceTypeCodeType"/>
 *         &lt;element name="invoiceCurrencyCode" type="{urn:gs1:shared:shared_common:xsd:3}CurrencyCodeType"/>
 *         &lt;element name="creditReasonCode" type="{urn:gs1:ecom:ecom_common:xsd:3}CreditReasonCodeType" minOccurs="0"/>
 *         &lt;element name="countryOfSupplyOfGoods" type="{urn:gs1:shared:shared_common:xsd:3}CountryCodeType" minOccurs="0"/>
 *         &lt;element name="supplierAccountReceivable" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="note" type="{urn:gs1:shared:shared_common:xsd:3}Description500Type" minOccurs="0"/>
 *         &lt;element name="buyer" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType"/>
 *         &lt;element name="seller" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType"/>
 *         &lt;element name="payer" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="payee" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="taxRepresentative" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="supplierCorporateOffice" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="supplierAgentRepresentative" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="remitTo" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="ultimateConsignee" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="shipFrom" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="shipTo" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="inventoryLocation" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="invoiceTotals" type="{urn:gs1:ecom:invoice:xsd:3}InvoiceTotalsType"/>
 *         &lt;element name="invoiceAllowanceCharge" type="{urn:gs1:ecom:invoice:xsd:3}InvoiceAllowanceChargeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="taxCurrencyInformation" type="{urn:gs1:shared:shared_common:xsd:3}CurrencyExchangeRateInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="payementTerms" type="{urn:gs1:ecom:ecom_common:xsd:3}PaymentTermsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="promotionalDeal" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="purchaseOrder" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="manifest" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="invoice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="salesOrder" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="despatchAdvice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="orderResponse" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="deliveryNote" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="receivingAdvice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="priceList" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="invoicingPeriod" type="{urn:gs1:shared:shared_common:xsd:3}DateTimeRangeType" minOccurs="0"/>
 *         &lt;element name="despatchInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}DespatchInformationType" minOccurs="0"/>
 *         &lt;element name="shipmentTransportationInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}ShipmentTransportationInformationType" minOccurs="0"/>
 *         &lt;element name="invoiceLineItem" type="{urn:gs1:ecom:invoice:xsd:3}InvoiceLineItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceType", propOrder = {
    "invoiceIdentification",
    "digitalSignature",
    "invoiceType",
    "invoiceCurrencyCode",
    "creditReasonCode",
    "countryOfSupplyOfGoods",
    "supplierAccountReceivable",
    "note",
    "buyer",
    "seller",
    "payer",
    "payee",
    "taxRepresentative",
    "supplierCorporateOffice",
    "supplierAgentRepresentative",
    "remitTo",
    "ultimateConsignee",
    "shipFrom",
    "shipTo",
    "inventoryLocation",
    "invoiceTotals",
    "invoiceAllowanceCharge",
    "taxCurrencyInformation",
    "paymentTerms",
    "promotionalDeal",
    "purchaseOrder",
    "manifest",
    "invoice",
    "salesOrder",
    "despatchAdvice",
    "orderResponse",
    "deliveryNote",
    "receivingAdvice",
    "priceList",
    "invoicingPeriod",
    "despatchInformation",
    "shipmentTransportationInformation",
    "invoiceLineItem"
})
public class InvoiceType
    extends EcomDocumentType
{

    @XmlElement(required = true)
    protected EntityIdentificationType invoiceIdentification;
    protected DigitalSignatureType digitalSignature;
    @XmlElement(required = true)
    protected InvoiceTypeCodeType invoiceType;
    @XmlElement(required = true)
    protected CurrencyCodeType invoiceCurrencyCode;
    protected CreditReasonCodeType creditReasonCode;
    protected CountryCodeType countryOfSupplyOfGoods;
    protected String supplierAccountReceivable;
    protected Description500Type note;
    @XmlElement(required = true)
    protected TransactionalPartyType buyer;
    @XmlElement(required = true)
    protected TransactionalPartyType seller;
    protected TransactionalPartyType payer;
    protected TransactionalPartyType payee;
    protected TransactionalPartyType taxRepresentative;
    protected TransactionalPartyType supplierCorporateOffice;
    protected TransactionalPartyType supplierAgentRepresentative;
    protected TransactionalPartyType remitTo;
    protected TransactionalPartyType ultimateConsignee;
    protected TransactionalPartyType shipFrom;
    protected TransactionalPartyType shipTo;
    protected TransactionalPartyType inventoryLocation;
    @XmlElement(required = true)
    protected InvoiceTotalsType invoiceTotals;
    protected List<InvoiceAllowanceChargeType> invoiceAllowanceCharge;
    protected List<CurrencyExchangeRateInformationType> taxCurrencyInformation;
    protected List<PaymentTermsType> paymentTerms;
    protected List<DocumentReferenceType> promotionalDeal;
    protected DocumentReferenceType purchaseOrder;
    protected DocumentReferenceType manifest;
    protected DocumentReferenceType invoice;
    protected DocumentReferenceType salesOrder;
    protected DocumentReferenceType despatchAdvice;
    protected DocumentReferenceType orderResponse;
    protected DocumentReferenceType deliveryNote;
    protected DocumentReferenceType receivingAdvice;
    protected DocumentReferenceType priceList;
    protected DateTimeRangeType invoicingPeriod;
    protected DespatchInformationType despatchInformation;
    protected ShipmentTransportationInformationType shipmentTransportationInformation;
    @XmlElement(required = true)
    protected List<InvoiceLineItemType> invoiceLineItem;

    /**
     * Gets the value of the invoiceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdentificationType }
     *     
     */
    public EntityIdentificationType getInvoiceIdentification() {
        return invoiceIdentification;
    }

    /**
     * Sets the value of the invoiceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdentificationType }
     *     
     */
    public void setInvoiceIdentification(EntityIdentificationType value) {
        this.invoiceIdentification = value;
    }

    /**
     * Gets the value of the digitalSignature property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalSignatureType }
     *     
     */
    public DigitalSignatureType getDigitalSignature() {
        return digitalSignature;
    }

    /**
     * Sets the value of the digitalSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalSignatureType }
     *     
     */
    public void setDigitalSignature(DigitalSignatureType value) {
        this.digitalSignature = value;
    }

    /**
     * Gets the value of the invoiceType property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTypeCodeType }
     *     
     */
    public InvoiceTypeCodeType getInvoiceType() {
        return invoiceType;
    }

    /**
     * Sets the value of the invoiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTypeCodeType }
     *     
     */
    public void setInvoiceType(InvoiceTypeCodeType value) {
        this.invoiceType = value;
    }

    /**
     * Gets the value of the invoiceCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeType }
     *     
     */
    public CurrencyCodeType getInvoiceCurrencyCode() {
        return invoiceCurrencyCode;
    }

    /**
     * Sets the value of the invoiceCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeType }
     *     
     */
    public void setInvoiceCurrencyCode(CurrencyCodeType value) {
        this.invoiceCurrencyCode = value;
    }

    /**
     * Gets the value of the creditReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link CreditReasonCodeType }
     *     
     */
    public CreditReasonCodeType getCreditReasonCode() {
        return creditReasonCode;
    }

    /**
     * Sets the value of the creditReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditReasonCodeType }
     *     
     */
    public void setCreditReasonCode(CreditReasonCodeType value) {
        this.creditReasonCode = value;
    }

    /**
     * Gets the value of the countryOfSupplyOfGoods property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getCountryOfSupplyOfGoods() {
        return countryOfSupplyOfGoods;
    }

    /**
     * Sets the value of the countryOfSupplyOfGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setCountryOfSupplyOfGoods(CountryCodeType value) {
        this.countryOfSupplyOfGoods = value;
    }

    /**
     * Gets the value of the supplierAccountReceivable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierAccountReceivable() {
        return supplierAccountReceivable;
    }

    /**
     * Sets the value of the supplierAccountReceivable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierAccountReceivable(String value) {
        this.supplierAccountReceivable = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Description500Type }
     *     
     */
    public Description500Type getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description500Type }
     *     
     */
    public void setNote(Description500Type value) {
        this.note = value;
    }

    /**
     * Gets the value of the buyer property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getBuyer() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setBuyer(TransactionalPartyType value) {
        this.buyer = value;
    }

    /**
     * Gets the value of the seller property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getSeller() {
        return seller;
    }

    /**
     * Sets the value of the seller property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setSeller(TransactionalPartyType value) {
        this.seller = value;
    }

    /**
     * Gets the value of the payer property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setPayer(TransactionalPartyType value) {
        this.payer = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setPayee(TransactionalPartyType value) {
        this.payee = value;
    }

    /**
     * Gets the value of the taxRepresentative property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getTaxRepresentative() {
        return taxRepresentative;
    }

    /**
     * Sets the value of the taxRepresentative property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setTaxRepresentative(TransactionalPartyType value) {
        this.taxRepresentative = value;
    }

    /**
     * Gets the value of the supplierCorporateOffice property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getSupplierCorporateOffice() {
        return supplierCorporateOffice;
    }

    /**
     * Sets the value of the supplierCorporateOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setSupplierCorporateOffice(TransactionalPartyType value) {
        this.supplierCorporateOffice = value;
    }

    /**
     * Gets the value of the supplierAgentRepresentative property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getSupplierAgentRepresentative() {
        return supplierAgentRepresentative;
    }

    /**
     * Sets the value of the supplierAgentRepresentative property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setSupplierAgentRepresentative(TransactionalPartyType value) {
        this.supplierAgentRepresentative = value;
    }

    /**
     * Gets the value of the remitTo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getRemitTo() {
        return remitTo;
    }

    /**
     * Sets the value of the remitTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setRemitTo(TransactionalPartyType value) {
        this.remitTo = value;
    }

    /**
     * Gets the value of the ultimateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getUltimateConsignee() {
        return ultimateConsignee;
    }

    /**
     * Sets the value of the ultimateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setUltimateConsignee(TransactionalPartyType value) {
        this.ultimateConsignee = value;
    }

    /**
     * Gets the value of the shipFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipFrom() {
        return shipFrom;
    }

    /**
     * Sets the value of the shipFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipFrom(TransactionalPartyType value) {
        this.shipFrom = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipTo(TransactionalPartyType value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the inventoryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getInventoryLocation() {
        return inventoryLocation;
    }

    /**
     * Sets the value of the inventoryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setInventoryLocation(TransactionalPartyType value) {
        this.inventoryLocation = value;
    }

    /**
     * Gets the value of the invoiceTotals property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTotalsType }
     *     
     */
    public InvoiceTotalsType getInvoiceTotals() {
        return invoiceTotals;
    }

    /**
     * Sets the value of the invoiceTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTotalsType }
     *     
     */
    public void setInvoiceTotals(InvoiceTotalsType value) {
        this.invoiceTotals = value;
    }

    /**
     * Gets the value of the invoiceAllowanceCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceAllowanceCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceAllowanceCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceAllowanceChargeType }
     * 
     * 
     */
    public List<InvoiceAllowanceChargeType> getInvoiceAllowanceCharge() {
        if (invoiceAllowanceCharge == null) {
            invoiceAllowanceCharge = new ArrayList<InvoiceAllowanceChargeType>();
        }
        return this.invoiceAllowanceCharge;
    }

    /**
     * Gets the value of the taxCurrencyInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxCurrencyInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxCurrencyInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyExchangeRateInformationType }
     * 
     * 
     */
    public List<CurrencyExchangeRateInformationType> getTaxCurrencyInformation() {
        if (taxCurrencyInformation == null) {
            taxCurrencyInformation = new ArrayList<CurrencyExchangeRateInformationType>();
        }
        return this.taxCurrencyInformation;
    }

    /**
     * Gets the value of the payementTerms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payementTerms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayementTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentTermsType }
     * 
     * 
     */
    public List<PaymentTermsType> getPaymentTerms() {
        if (paymentTerms == null) {
            paymentTerms = new ArrayList<PaymentTermsType>();
        }
        return this.paymentTerms;
    }

    /**
     * Gets the value of the promotionalDeal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionalDeal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionalDeal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentReferenceType }
     * 
     * 
     */
    public List<DocumentReferenceType> getPromotionalDeal() {
        if (promotionalDeal == null) {
            promotionalDeal = new ArrayList<DocumentReferenceType>();
        }
        return this.promotionalDeal;
    }

    /**
     * Gets the value of the purchaseOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getPurchaseOrder() {
        return purchaseOrder;
    }

    /**
     * Sets the value of the purchaseOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setPurchaseOrder(DocumentReferenceType value) {
        this.purchaseOrder = value;
    }

    /**
     * Gets the value of the manifest property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getManifest() {
        return manifest;
    }

    /**
     * Sets the value of the manifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setManifest(DocumentReferenceType value) {
        this.manifest = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setInvoice(DocumentReferenceType value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the salesOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getSalesOrder() {
        return salesOrder;
    }

    /**
     * Sets the value of the salesOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setSalesOrder(DocumentReferenceType value) {
        this.salesOrder = value;
    }

    /**
     * Gets the value of the despatchAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getDespatchAdvice() {
        return despatchAdvice;
    }

    /**
     * Sets the value of the despatchAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setDespatchAdvice(DocumentReferenceType value) {
        this.despatchAdvice = value;
    }

    /**
     * Gets the value of the orderResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getOrderResponse() {
        return orderResponse;
    }

    /**
     * Sets the value of the orderResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setOrderResponse(DocumentReferenceType value) {
        this.orderResponse = value;
    }

    /**
     * Gets the value of the deliveryNote property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getDeliveryNote() {
        return deliveryNote;
    }

    /**
     * Sets the value of the deliveryNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setDeliveryNote(DocumentReferenceType value) {
        this.deliveryNote = value;
    }

    /**
     * Gets the value of the receivingAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getReceivingAdvice() {
        return receivingAdvice;
    }

    /**
     * Sets the value of the receivingAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setReceivingAdvice(DocumentReferenceType value) {
        this.receivingAdvice = value;
    }

    /**
     * Gets the value of the priceList property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getPriceList() {
        return priceList;
    }

    /**
     * Sets the value of the priceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setPriceList(DocumentReferenceType value) {
        this.priceList = value;
    }

    /**
     * Gets the value of the invoicingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRangeType }
     *     
     */
    public DateTimeRangeType getInvoicingPeriod() {
        return invoicingPeriod;
    }

    /**
     * Sets the value of the invoicingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRangeType }
     *     
     */
    public void setInvoicingPeriod(DateTimeRangeType value) {
        this.invoicingPeriod = value;
    }

    /**
     * Gets the value of the despatchInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DespatchInformationType }
     *     
     */
    public DespatchInformationType getDespatchInformation() {
        return despatchInformation;
    }

    /**
     * Sets the value of the despatchInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DespatchInformationType }
     *     
     */
    public void setDespatchInformation(DespatchInformationType value) {
        this.despatchInformation = value;
    }

    /**
     * Gets the value of the shipmentTransportationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentTransportationInformationType }
     *     
     */
    public ShipmentTransportationInformationType getShipmentTransportationInformation() {
        return shipmentTransportationInformation;
    }

    /**
     * Sets the value of the shipmentTransportationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentTransportationInformationType }
     *     
     */
    public void setShipmentTransportationInformation(ShipmentTransportationInformationType value) {
        this.shipmentTransportationInformation = value;
    }

    /**
     * Gets the value of the invoiceLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceLineItemType }
     * 
     * 
     */
    public List<InvoiceLineItemType> getInvoiceLineItem() {
        if (invoiceLineItem == null) {
            invoiceLineItem = new ArrayList<InvoiceLineItemType>();
        }
        return this.invoiceLineItem;
    }

}
