ALTER TABLE I_Coda ADD XX_SchemaCarte CHAR(1);
ALTER TABLE I_Coda ADD XX_Terminal NVARCHAR2(10);
ALTER TABLE I_Coda ADD XX_DateTrx NVARCHAR2(22);
ALTER TABLE I_Coda ADD XX_BrutAmt NUMBER;
ALTER TABLE I_Coda ADD XX_CmsAmt NUMBER;
ALTER TABLE I_Coda ADD XX_Projet NVARCHAR2(20);
ALTER TABLE I_Coda ADD C_Order_ID NUMBER(10);
ALTER TABLE I_Coda ADD CONSTRAINT FK1000973_1032173 FOREIGN KEY (C_Order_ID) REFERENCES C_Order (C_Order_ID);