CREATE TABLE "I_POSORDER"
  (
    "AD_CLIENT_ID"       NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"          NUMBER(10,0) NOT NULL ENABLE,
    "C_BPARTNER_ID"      NUMBER(10,0) NOT NULL ENABLE,
    "C_DOCTYPETARGET_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDER_ID"         NUMBER(10,0),
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DATEORDERED" DATE NOT NULL ENABLE,
    "DOCUMENTNO" NVARCHAR2(30) DEFAULT NULL NOT NULL ENABLE,
    "GRANDTOTAL" NUMBER DEFAULT 0 NOT NULL ENABLE,
    "I_ERRORMSG" NVARCHAR2(2000),
    "I_ISIMPORTED"  CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "I_POSORDER_ID" NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"      CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "PROCESSED"     CHAR(1 BYTE) DEFAULT 'N',
    "PROCESSING"    CHAR(1 BYTE) DEFAULT 'N',
    "SALESREP_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_POSNBR" NVARCHAR2(22) NOT NULL ENABLE,
    "PRIORITY"               NUMBER(10,0) DEFAULT 0,
    "C_BPARTNER_LOCATION_ID" NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive  IN ('Y','N')) ENABLE,
    CHECK (Processed IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000645" PRIMARY KEY ("I_POSORDER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK1000645_1005568" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
CREATE TABLE "I_POSORDERLINE"
  (
    "AD_CLIENT_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"      NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDERLINE_ID" NUMBER(10,0),
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY"         NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "I_POSORDER_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "I_POSORDERLINE_ID" NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"          CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "M_PRODUCT_ID"      NUMBER(10,0),
    "PRICEENTERED"      NUMBER DEFAULT 0 NOT NULL ENABLE,
    "PRICELIST"         NUMBER DEFAULT 0 NOT NULL ENABLE,
    "QTYENTERED"        NUMBER DEFAULT 1 NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_POSNBR" NVARCHAR2(22) DEFAULT NULL,
    "Z_SERNO" NVARCHAR2(40),
    "LINE" NUMBER(10,0) NOT NULL ENABLE,
    "Z_REFERENCEART" NVARCHAR2(30),
    "Z_PRODDESCRIPTION" NVARCHAR2(400),
    "M_PRODUCT_CATEGORY_ID" NUMBER(10,0),
    "FOURNISSEUR" NVARCHAR2(60),
    "Y_MARQUE_ID"        NUMBER(10,0),
    "PRODUCT_PRICE"      NUMBER,
    "Z_S_FAMILLE_ID"     NUMBER(10,0),
    "Z_S_S_FAMILLE_ID"   NUMBER(10,0),
    "Z_S_S_S_FAMILLE_ID" NUMBER(10,0),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000745" PRIMARY KEY ("I_POSORDERLINE_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK1000745_1005671" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE,
    CONSTRAINT "FK1000745_1006162" FOREIGN KEY ("Z_S_FAMILLE_ID") REFERENCES "Z_S_FAMILLE" ("Z_S_FAMILLE_ID") ENABLE,
    CONSTRAINT "FK1000745_1006163" FOREIGN KEY ("Z_S_S_FAMILLE_ID") REFERENCES "Z_S_S_FAMILLE" ("Z_S_S_FAMILLE_ID") ENABLE,
    CONSTRAINT "FK1000745_1006164" FOREIGN KEY ("Z_S_S_S_FAMILLE_ID") REFERENCES "Z_S_S_S_FAMILLE" ("Z_S_S_S_FAMILLE_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;  
  CREATE TABLE "I_POSORDERLINEACTION"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "COMMENTS" NVARCHAR2(2000) DEFAULT NULL,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DATEACTION" DATE,
    "I_POSORDERLINEACTION_ID" NUMBER(10,0) NOT NULL ENABLE,
    "I_POSORDERLINE_ID"       NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"                CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "QTYENTERED"              NUMBER DEFAULT 0,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"               NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "AD_ORGTO_ID"             NUMBER(10,0),
    "Z_POSWFACTION_ID"        NUMBER(10,0) NOT NULL ENABLE,
    "Z_ORDERLINEPOSACTION_ID" NUMBER(10,0),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000746" PRIMARY KEY ("I_POSORDERLINEACTION_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK1000746_1005799" FOREIGN KEY ("AD_ORGTO_ID") REFERENCES "AD_ORG" ("AD_ORG_ID") ENABLE,
    CONSTRAINT "FK1000746_1005698" FOREIGN KEY ("Z_POSWFACTION_ID") REFERENCES "Z_POSWFACTION" ("Z_POSWFACTION_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  CREATE TABLE "I_POSORDERPAYMENT"
  (
    "AD_CLIENT_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"        NUMBER(10,0) NOT NULL ENABLE,
    "C_BANKACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_DOCTYPE_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY"            NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "I_POSORDER_ID"        NUMBER(10,0) NOT NULL ENABLE,
    "I_POSORDERPAYMENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"             CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "PAYAMT"               NUMBER DEFAULT 0,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"          NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "ZSUBPAYMENTRULE_ID" NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000747" PRIMARY KEY ("I_POSORDERPAYMENT_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  CREATE TABLE "Z_POSACTIONACTIVITY"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "ISACTIVE"  CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "SEQNO"     NUMBER(10,0) NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"              NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_POSACTIONACTIVITY_ID" NUMBER(10,0) NOT NULL ENABLE,
    "Z_POSWFACTION_ID"       NUMBER(10,0) NOT NULL ENABLE,
    "Z_POSWFACTIVITY_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "ISVALIDATEDBYORGFROM"   CHAR(1 BYTE) DEFAULT 'N',
    "ISVALIDATEDBYORGTO"     CHAR(1 BYTE) DEFAULT 'N',
    "ISSTOCKED"              CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "M_LOCATOR_ID"           NUMBER(10,0),
    "ISMVTIN"                CHAR(1 BYTE) DEFAULT 'N',
    "AD_ROLE_ID"             NUMBER(10,0),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000849" PRIMARY KEY ("Z_POSACTIONACTIVITY_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CHECK (IsValidatedByOrgFrom IN ('Y','N')) ENABLE,
    CHECK (IsValidatedByOrgTo   IN ('Y','N')) ENABLE,
    CHECK (IsStocked            IN ('Y','N')) ENABLE,
    CHECK (IsMvtIn              IN ('Y','N')) ENABLE,
    CONSTRAINT "FK1000849_1005934" FOREIGN KEY ("Z_POSWFACTIVITY_ID") REFERENCES "Z_POSWFACTIVITY" ("Z_POSWFACTIVITY_ID") ENABLE,
    CONSTRAINT "FK1000849_1006553" FOREIGN KEY ("AD_ROLE_ID") REFERENCES "AD_ROLE" ("AD_ROLE_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  CREATE TABLE "Z_POSWFACTION"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DESCRIPTION" NVARCHAR2(60),
    "ISACTIVE"            CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ISDATEORCMTREQUIRED" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "SEQNO"               NUMBER(10,0),
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "VALUE" NVARCHAR2(22) NOT NULL ENABLE,
    "Z_POSWFACTION_ID" NUMBER(10,0) NOT NULL ENABLE,
    "ISTOORGREQUIRED"  CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "ISSTOCKED"        CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "ISMVTIN"          CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "M_LOCATOR_ID"     NUMBER(10,0),
    "GENERATEMSG"      CHAR(1 BYTE) DEFAULT 'N',
    "ISSAVACTION"      CHAR(1 BYTE) DEFAULT 'N',
    CHECK (IsActive            IN ('Y','N')) ENABLE,
    CHECK (IsDateOrCmtRequired IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000848" PRIMARY KEY ("Z_POSWFACTION_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CHECK (IsToOrgRequired IN ('Y','N')) ENABLE,
    CHECK (IsStocked       IN ('Y','N')) ENABLE,
    CHECK (IsMvtIn         IN ('Y','N')) ENABLE,
    CHECK (GenerateMsg     IN ('Y','N')) ENABLE,
    CHECK (IsSavAction     IN ('Y','N')) ENABLE,
    CONSTRAINT "FK1000848_1005912" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  CREATE TABLE "Z_POSWFACTIVITY"
  (
    "AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DESCRIPTION" NVARCHAR2(60),
    "ISACTIVE"       CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ISPOSUPDATABLE" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "VALUE" NVARCHAR2(22) NOT NULL ENABLE,
    "Z_POSWFACTIVITY_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "AD_ROLE_ID"           NUMBER(10,0) DEFAULT NULL,
    "ISVALIDATEDBYORGFROM" CHAR(1 BYTE) DEFAULT 'N',
    "ISVALIDATEDBYORGTO"   CHAR(1 BYTE) DEFAULT 'N',
    CHECK (IsActive       IN ('Y','N')) ENABLE,
    CHECK (IsPOSUpdatable IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000847" PRIMARY KEY ("Z_POSWFACTIVITY_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CHECK (IsValidatedByOrgFrom IN ('Y','N')) ENABLE,
    CHECK (IsValidatedByOrgTo   IN ('Y','N')) ENABLE,
    CONSTRAINT "FK1000847_1006180" FOREIGN KEY ("AD_ROLE_ID") REFERENCES "AD_ROLE" ("AD_ROLE_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
CREATE TABLE "Z_TRANSACTIONMSG"
  (
    "ACTIONCOMMENT" NVARCHAR2(2000),
    "ACTIONDATE" DATE,
    "AD_CLIENT_ID"  NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORGTO_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORGTRX_ID"  NUMBER(10,0),
    "C_BPARTNER_ID" NUMBER(10,0),
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "DOCUMENTNO" NVARCHAR2(30) NOT NULL ENABLE,
    "ISACTIVE"     CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "LINE"         NUMBER(10,0),
    "M_PRODUCT_ID" NUMBER(10,0),
    "PORECEIPTNO" NVARCHAR2(30),
    "PROCESSCOMMENT" NVARCHAR2(2000),
    "PROCESSING" CHAR(1 BYTE) DEFAULT 'N',
    "PURCHASEORDERNO" NVARCHAR2(30),
    "QUANTITY" NUMBER DEFAULT 1 NOT NULL ENABLE,
    "REQUISITIONNO" NVARCHAR2(30),
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"           NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_TRANSACTIONMSG_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDERLINE_ID"      NUMBER(10,0) DEFAULT NULL,
    "Z_POSWFACTION_ID"    NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    "Z_POSWFACTIVITY_ID"  NUMBER(10,0) NOT NULL ENABLE,
    "Z_REFERENCEART" NVARCHAR2(30),
    "Z_PRODDESCRIPTION" NVARCHAR2(400),
    "M_PRODUCT_CATEGORY_ID" NUMBER(10,0),
    "FOURNISSEUR" NVARCHAR2(60),
    "Y_MARQUE_ID"        NUMBER(10,0),
    "PRODUCT_PRICE"      NUMBER,
    "PRODUCT_CREATED_ID" NUMBER(10,0),
    "ISVALIDATEDREQUEST" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "ISCANCELREQUEST"    CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "ERRORMSG" NVARCHAR2(2000),
    "ISPROCESSED"        CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    "INITIALMSGID"       NUMBER(10,0),
    "Z_S_FAMILLE_ID"     NUMBER(10,0),
    "Z_S_S_FAMILLE_ID"   NUMBER(10,0),
    "Z_S_S_S_FAMILLE_ID" NUMBER(10,0),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000846" PRIMARY KEY ("Z_TRANSACTIONMSG_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CHECK (IsValidatedRequest IN ('Y','N')) ENABLE,
    CHECK (IsCancelRequest    IN ('Y','N')) ENABLE,
    CONSTRAINT "FK1000846_1005951" FOREIGN KEY ("Z_POSWFACTION_ID") REFERENCES "Z_POSWFACTION" ("Z_POSWFACTION_ID") ENABLE,
    CONSTRAINT "FK1000846_1005952" FOREIGN KEY ("Z_POSWFACTIVITY_ID") REFERENCES "Z_POSWFACTIVITY" ("Z_POSWFACTIVITY_ID") ENABLE,
    CONSTRAINT "FK1000846_1006177" FOREIGN KEY ("PRODUCT_CREATED_ID") REFERENCES "M_PRODUCT" ("M_PRODUCT_ID") ENABLE,
    CONSTRAINT "FK1000846_1006171" FOREIGN KEY ("Z_S_FAMILLE_ID") REFERENCES "Z_S_FAMILLE" ("Z_S_FAMILLE_ID") ENABLE,
    CONSTRAINT "FK1000846_1006172" FOREIGN KEY ("Z_S_S_FAMILLE_ID") REFERENCES "Z_S_S_FAMILLE" ("Z_S_S_FAMILLE_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  CREATE TABLE "Z_ORDERLINEPOSACTION"
  (
    "AD_CLIENT_ID"   NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"      NUMBER(10,0) NOT NULL ENABLE,
    "C_ORDERLINE_ID" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY"  NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "ISACTIVE"   CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "QTYENTERED" NUMBER DEFAULT 0,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"           NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
    "Z_POSWFACTION_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "Z_TRANSACTIONMSG_ID" NUMBER(10,0) DEFAULT NULL,
    "COMMENTS" NVARCHAR2(2000) DEFAULT NULL,
    "DATEACTION" DATE DEFAULT NULL,
    "AD_ORGTO_ID"             NUMBER(10,0),
    "Z_ORDERLINEPOSACTION_ID" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "PK1000850" PRIMARY KEY ("Z_ORDERLINEPOSACTION_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "FK1000850_1005935" FOREIGN KEY ("AD_CLIENT_ID") REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE,
    CONSTRAINT "FK1000850_1005948" FOREIGN KEY ("AD_ORGTO_ID") REFERENCES "AD_ORG" ("AD_ORG_ID") ENABLE,
    CONSTRAINT "FK1000850_1005942" FOREIGN KEY ("C_ORDERLINE_ID") REFERENCES "C_ORDERLINE" ("C_ORDERLINE_ID") ON
  DELETE CASCADE ENABLE
  );