//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//


package gs1.ecom.invoice.xsd._3;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import gs1.ecom.ecom_common.xsd._3.ConsignmentReferenceType;
import gs1.ecom.ecom_common.xsd._3.CreditReasonCodeType;
import gs1.ecom.ecom_common.xsd._3.DespatchInformationType;
import gs1.ecom.ecom_common.xsd._3.EcomAttributeValuePairListType;
import gs1.ecom.ecom_common.xsd._3.LeviedDutyFeeTaxType;
import gs1.ecom.ecom_common.xsd._3.LogisticServiceReferenceType;
import gs1.ecom.ecom_common.xsd._3.MarginSchemeCodeType;
import gs1.ecom.ecom_common.xsd._3.ShipmentReferenceType;
import gs1.ecom.ecom_common.xsd._3.TransactionalPartyType;
import gs1.ecom.ecom_common.xsd._3.TransactionalTradeItemType;
import gs1.shared.shared_common.xsd._3.AmountType;
import gs1.shared.shared_common.xsd._3.DateTimeRangeType;
import gs1.shared.shared_common.xsd._3.Description1000Type;
import gs1.shared.shared_common.xsd._3.Description200Type;
import gs1.shared.shared_common.xsd._3.Description500Type;
import gs1.shared.shared_common.xsd._3.DocumentReferenceType;
import gs1.shared.shared_common.xsd._3.QuantityType;


/**
 * <p>Java class for InvoiceLineItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceLineItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineItemNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="parentLineItemNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="invoicedQuantity" type="{urn:gs1:shared:shared_common:xsd:3}QuantityType"/>
 *         &lt;element name="amountExclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="amountInclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="deliveredQuantity" type="{urn:gs1:shared:shared_common:xsd:3}QuantityType" minOccurs="0"/>
 *         &lt;element name="creditLineIndicator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="creditReason" type="{urn:gs1:ecom:ecom_common:xsd:3}CreditReasonCodeType" minOccurs="0"/>
 *         &lt;element name="excludedFromPaymentDiscountIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="itemPriceBaseQuantity" type="{urn:gs1:shared:shared_common:xsd:3}QuantityType" minOccurs="0"/>
 *         &lt;element name="itemPriceExclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="itemPriceInclusiveAllowancesCharges" type="{urn:gs1:shared:shared_common:xsd:3}AmountType" minOccurs="0"/>
 *         &lt;element name="marginSchemeInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}MarginSchemeCodeType" minOccurs="0"/>
 *         &lt;element name="marginSchemeDescription" type="{urn:gs1:shared:shared_common:xsd:3}Description200Type" minOccurs="0"/>
 *         &lt;element name="transferOfOwnershipDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="additionalOrderLineInstruction" type="{urn:gs1:shared:shared_common:xsd:3}Description1000Type" minOccurs="0"/>
 *         &lt;element name="note" type="{urn:gs1:shared:shared_common:xsd:3}Description500Type" minOccurs="0"/>
 *         &lt;element name="transactionalTradeItem" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalTradeItemType"/>
 *         &lt;element name="invoiceAllowanceCharge" type="{urn:gs1:ecom:invoice:xsd:3}InvoiceAllowanceChargeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="invoiceLineTaxInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}LeviedDutyFeeTaxType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="invoiceLineItemInformationAfterTaxes" type="{urn:gs1:ecom:invoice:xsd:3}InvoiceLineItemInformationAfterTaxesType" minOccurs="0"/>
 *         &lt;element name="despatchInformation" type="{urn:gs1:ecom:ecom_common:xsd:3}DespatchInformationType" minOccurs="0"/>
 *         &lt;element name="shipTo" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="shipFrom" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="inventoryLocationTo" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="inventoryLocationFrom" type="{urn:gs1:ecom:ecom_common:xsd:3}TransactionalPartyType" minOccurs="0"/>
 *         &lt;element name="servicetimePeriodLineLevel" type="{urn:gs1:shared:shared_common:xsd:3}DateTimeRangeType" minOccurs="0"/>
 *         &lt;element name="deliveryNote" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="purchaseOrder" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="salesOrder" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="receivingAdvice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="promotionalDeal" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="purchaseConditions" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="despatchAdvice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="invoice" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="consumptionReport" type="{urn:gs1:shared:shared_common:xsd:3}DocumentReferenceType" minOccurs="0"/>
 *         &lt;element name="logisticServiceReference" type="{urn:gs1:ecom:ecom_common:xsd:3}LogisticServiceReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="consignmentReference" type="{urn:gs1:ecom:ecom_common:xsd:3}ConsignmentReferenceType" minOccurs="0"/>
 *         &lt;element name="shipmentReference" type="{urn:gs1:ecom:ecom_common:xsd:3}ShipmentReferenceType" minOccurs="0"/>
 *         &lt;element name="avpList" type="{urn:gs1:ecom:ecom_common:xsd:3}Ecom_AttributeValuePairListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceLineItemType", propOrder = {
    "lineItemNumber",
    "parentLineItemNumber",
    "invoicedQuantity",
    "amountExclusiveAllowancesCharges",
    "amountInclusiveAllowancesCharges",
    "deliveredQuantity",
    "creditLineIndicator",
    "creditReason",
    "excludedFromPaymentDiscountIndicator",
    "itemPriceBaseQuantity",
    "itemPriceExclusiveAllowancesCharges",
    "itemPriceInclusiveAllowancesCharges",
    "marginSchemeInformation",
    "marginSchemeDescription",
    "transferOfOwnershipDate",
    "additionalOrderLineInstruction",
    "note",
    "transactionalTradeItem",
    "invoiceAllowanceCharge",
    "invoiceLineTaxInformation",
    "invoiceLineItemInformationAfterTaxes",
    "despatchInformation",
    "shipTo",
    "shipFrom",
    "inventoryLocationTo",
    "inventoryLocationFrom",
    "servicetimePeriodLineLevel",
    "deliveryNote",
    "purchaseOrder",
    "salesOrder",
    "receivingAdvice",
    "promotionalDeal",
    "purchaseConditions",
    "despatchAdvice",
    "invoice",
    "consumptionReport",
    "logisticServiceReference",
    "consignmentReference",
    "shipmentReference",
    "avpList"
})
public class InvoiceLineItemType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lineItemNumber;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger parentLineItemNumber;
    @XmlElement(required = true)
    protected QuantityType invoicedQuantity;
    protected AmountType amountExclusiveAllowancesCharges;
    protected AmountType amountInclusiveAllowancesCharges;
    protected QuantityType deliveredQuantity;
    protected String creditLineIndicator;
    protected CreditReasonCodeType creditReason;
    protected Boolean excludedFromPaymentDiscountIndicator;
    protected QuantityType itemPriceBaseQuantity;
    protected AmountType itemPriceExclusiveAllowancesCharges;
    protected AmountType itemPriceInclusiveAllowancesCharges;
    protected MarginSchemeCodeType marginSchemeInformation;
    protected Description200Type marginSchemeDescription;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar transferOfOwnershipDate;
    protected Description1000Type additionalOrderLineInstruction;
    protected Description500Type note;
    @XmlElement(required = true)
    protected TransactionalTradeItemType transactionalTradeItem;
    protected List<InvoiceAllowanceChargeType> invoiceAllowanceCharge;
    protected List<LeviedDutyFeeTaxType> invoiceLineTaxInformation;
    protected InvoiceLineItemInformationAfterTaxesType invoiceLineItemInformationAfterTaxes;
    protected DespatchInformationType despatchInformation;
    protected TransactionalPartyType shipTo;
    protected TransactionalPartyType shipFrom;
    protected TransactionalPartyType inventoryLocationTo;
    protected TransactionalPartyType inventoryLocationFrom;
    protected DateTimeRangeType servicetimePeriodLineLevel;
    protected DocumentReferenceType deliveryNote;
    protected DocumentReferenceType purchaseOrder;
    protected DocumentReferenceType salesOrder;
    protected DocumentReferenceType receivingAdvice;
    protected DocumentReferenceType promotionalDeal;
    protected DocumentReferenceType purchaseConditions;
    protected DocumentReferenceType despatchAdvice;
    protected DocumentReferenceType invoice;
    protected DocumentReferenceType consumptionReport;
    protected List<LogisticServiceReferenceType> logisticServiceReference;
    protected ConsignmentReferenceType consignmentReference;
    protected ShipmentReferenceType shipmentReference;
    protected EcomAttributeValuePairListType avpList;

    /**
     * Gets the value of the lineItemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineItemNumber() {
        return lineItemNumber;
    }

    /**
     * Sets the value of the lineItemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineItemNumber(BigInteger value) {
        this.lineItemNumber = value;
    }

    /**
     * Gets the value of the parentLineItemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentLineItemNumber() {
        return parentLineItemNumber;
    }

    /**
     * Sets the value of the parentLineItemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentLineItemNumber(BigInteger value) {
        this.parentLineItemNumber = value;
    }

    /**
     * Gets the value of the invoicedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getInvoicedQuantity() {
        return invoicedQuantity;
    }

    /**
     * Sets the value of the invoicedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setInvoicedQuantity(QuantityType value) {
        this.invoicedQuantity = value;
    }

    /**
     * Gets the value of the amountExclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmountExclusiveAllowancesCharges() {
        return amountExclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the amountExclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmountExclusiveAllowancesCharges(AmountType value) {
        this.amountExclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the amountInclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmountInclusiveAllowancesCharges() {
        return amountInclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the amountInclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmountInclusiveAllowancesCharges(AmountType value) {
        this.amountInclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the deliveredQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getDeliveredQuantity() {
        return deliveredQuantity;
    }

    /**
     * Sets the value of the deliveredQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setDeliveredQuantity(QuantityType value) {
        this.deliveredQuantity = value;
    }

    /**
     * Gets the value of the creditLineIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLineIndicator() {
        return creditLineIndicator;
    }

    /**
     * Sets the value of the creditLineIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLineIndicator(String value) {
        this.creditLineIndicator = value;
    }

    /**
     * Gets the value of the creditReason property.
     * 
     * @return
     *     possible object is
     *     {@link CreditReasonCodeType }
     *     
     */
    public CreditReasonCodeType getCreditReason() {
        return creditReason;
    }

    /**
     * Sets the value of the creditReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditReasonCodeType }
     *     
     */
    public void setCreditReason(CreditReasonCodeType value) {
        this.creditReason = value;
    }

    /**
     * Gets the value of the excludedFromPaymentDiscountIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExcludedFromPaymentDiscountIndicator() {
        return excludedFromPaymentDiscountIndicator;
    }

    /**
     * Sets the value of the excludedFromPaymentDiscountIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludedFromPaymentDiscountIndicator(Boolean value) {
        this.excludedFromPaymentDiscountIndicator = value;
    }

    /**
     * Gets the value of the itemPriceBaseQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getItemPriceBaseQuantity() {
        return itemPriceBaseQuantity;
    }

    /**
     * Sets the value of the itemPriceBaseQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setItemPriceBaseQuantity(QuantityType value) {
        this.itemPriceBaseQuantity = value;
    }

    /**
     * Gets the value of the itemPriceExclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getItemPriceExclusiveAllowancesCharges() {
        return itemPriceExclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the itemPriceExclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setItemPriceExclusiveAllowancesCharges(AmountType value) {
        this.itemPriceExclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the itemPriceInclusiveAllowancesCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getItemPriceInclusiveAllowancesCharges() {
        return itemPriceInclusiveAllowancesCharges;
    }

    /**
     * Sets the value of the itemPriceInclusiveAllowancesCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setItemPriceInclusiveAllowancesCharges(AmountType value) {
        this.itemPriceInclusiveAllowancesCharges = value;
    }

    /**
     * Gets the value of the marginSchemeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MarginSchemeCodeType }
     *     
     */
    public MarginSchemeCodeType getMarginSchemeInformation() {
        return marginSchemeInformation;
    }

    /**
     * Sets the value of the marginSchemeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarginSchemeCodeType }
     *     
     */
    public void setMarginSchemeInformation(MarginSchemeCodeType value) {
        this.marginSchemeInformation = value;
    }

    /**
     * Gets the value of the marginSchemeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Description200Type }
     *     
     */
    public Description200Type getMarginSchemeDescription() {
        return marginSchemeDescription;
    }

    /**
     * Sets the value of the marginSchemeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description200Type }
     *     
     */
    public void setMarginSchemeDescription(Description200Type value) {
        this.marginSchemeDescription = value;
    }

    /**
     * Gets the value of the transferOfOwnershipDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransferOfOwnershipDate() {
        return transferOfOwnershipDate;
    }

    /**
     * Sets the value of the transferOfOwnershipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransferOfOwnershipDate(XMLGregorianCalendar value) {
        this.transferOfOwnershipDate = value;
    }

    /**
     * Gets the value of the additionalOrderLineInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link Description1000Type }
     *     
     */
    public Description1000Type getAdditionalOrderLineInstruction() {
        return additionalOrderLineInstruction;
    }

    /**
     * Sets the value of the additionalOrderLineInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description1000Type }
     *     
     */
    public void setAdditionalOrderLineInstruction(Description1000Type value) {
        this.additionalOrderLineInstruction = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Description500Type }
     *     
     */
    public Description500Type getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description500Type }
     *     
     */
    public void setNote(Description500Type value) {
        this.note = value;
    }

    /**
     * Gets the value of the transactionalTradeItem property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalTradeItemType }
     *     
     */
    public TransactionalTradeItemType getTransactionalTradeItem() {
        return transactionalTradeItem;
    }

    /**
     * Sets the value of the transactionalTradeItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalTradeItemType }
     *     
     */
    public void setTransactionalTradeItem(TransactionalTradeItemType value) {
        this.transactionalTradeItem = value;
    }

    /**
     * Gets the value of the invoiceAllowanceCharge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceAllowanceCharge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceAllowanceCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceAllowanceChargeType }
     * 
     * 
     */
    public List<InvoiceAllowanceChargeType> getInvoiceAllowanceCharge() {
        if (invoiceAllowanceCharge == null) {
            invoiceAllowanceCharge = new ArrayList<InvoiceAllowanceChargeType>();
        }
        return this.invoiceAllowanceCharge;
    }

    /**
     * Gets the value of the invoiceLineTaxInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceLineTaxInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceLineTaxInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeviedDutyFeeTaxType }
     * 
     * 
     */
    public List<LeviedDutyFeeTaxType> getInvoiceLineTaxInformation() {
        if (invoiceLineTaxInformation == null) {
            invoiceLineTaxInformation = new ArrayList<LeviedDutyFeeTaxType>();
        }
        return this.invoiceLineTaxInformation;
    }

    /**
     * Gets the value of the invoiceLineItemInformationAfterTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceLineItemInformationAfterTaxesType }
     *     
     */
    public InvoiceLineItemInformationAfterTaxesType getInvoiceLineItemInformationAfterTaxes() {
        return invoiceLineItemInformationAfterTaxes;
    }

    /**
     * Sets the value of the invoiceLineItemInformationAfterTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceLineItemInformationAfterTaxesType }
     *     
     */
    public void setInvoiceLineItemInformationAfterTaxes(InvoiceLineItemInformationAfterTaxesType value) {
        this.invoiceLineItemInformationAfterTaxes = value;
    }

    /**
     * Gets the value of the despatchInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DespatchInformationType }
     *     
     */
    public DespatchInformationType getDespatchInformation() {
        return despatchInformation;
    }

    /**
     * Sets the value of the despatchInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DespatchInformationType }
     *     
     */
    public void setDespatchInformation(DespatchInformationType value) {
        this.despatchInformation = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipTo(TransactionalPartyType value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the shipFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getShipFrom() {
        return shipFrom;
    }

    /**
     * Sets the value of the shipFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setShipFrom(TransactionalPartyType value) {
        this.shipFrom = value;
    }

    /**
     * Gets the value of the inventoryLocationTo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getInventoryLocationTo() {
        return inventoryLocationTo;
    }

    /**
     * Sets the value of the inventoryLocationTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setInventoryLocationTo(TransactionalPartyType value) {
        this.inventoryLocationTo = value;
    }

    /**
     * Gets the value of the inventoryLocationFrom property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalPartyType }
     *     
     */
    public TransactionalPartyType getInventoryLocationFrom() {
        return inventoryLocationFrom;
    }

    /**
     * Sets the value of the inventoryLocationFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalPartyType }
     *     
     */
    public void setInventoryLocationFrom(TransactionalPartyType value) {
        this.inventoryLocationFrom = value;
    }

    /**
     * Gets the value of the servicetimePeriodLineLevel property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRangeType }
     *     
     */
    public DateTimeRangeType getServicetimePeriodLineLevel() {
        return servicetimePeriodLineLevel;
    }

    /**
     * Sets the value of the servicetimePeriodLineLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRangeType }
     *     
     */
    public void setServicetimePeriodLineLevel(DateTimeRangeType value) {
        this.servicetimePeriodLineLevel = value;
    }

    /**
     * Gets the value of the deliveryNote property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getDeliveryNote() {
        return deliveryNote;
    }

    /**
     * Sets the value of the deliveryNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setDeliveryNote(DocumentReferenceType value) {
        this.deliveryNote = value;
    }

    /**
     * Gets the value of the purchaseOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getPurchaseOrder() {
        return purchaseOrder;
    }

    /**
     * Sets the value of the purchaseOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setPurchaseOrder(DocumentReferenceType value) {
        this.purchaseOrder = value;
    }

    /**
     * Gets the value of the salesOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getSalesOrder() {
        return salesOrder;
    }

    /**
     * Sets the value of the salesOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setSalesOrder(DocumentReferenceType value) {
        this.salesOrder = value;
    }

    /**
     * Gets the value of the receivingAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getReceivingAdvice() {
        return receivingAdvice;
    }

    /**
     * Sets the value of the receivingAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setReceivingAdvice(DocumentReferenceType value) {
        this.receivingAdvice = value;
    }

    /**
     * Gets the value of the promotionalDeal property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getPromotionalDeal() {
        return promotionalDeal;
    }

    /**
     * Sets the value of the promotionalDeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setPromotionalDeal(DocumentReferenceType value) {
        this.promotionalDeal = value;
    }

    /**
     * Gets the value of the purchaseConditions property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getPurchaseConditions() {
        return purchaseConditions;
    }

    /**
     * Sets the value of the purchaseConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setPurchaseConditions(DocumentReferenceType value) {
        this.purchaseConditions = value;
    }

    /**
     * Gets the value of the despatchAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getDespatchAdvice() {
        return despatchAdvice;
    }

    /**
     * Sets the value of the despatchAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setDespatchAdvice(DocumentReferenceType value) {
        this.despatchAdvice = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setInvoice(DocumentReferenceType value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the consumptionReport property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getConsumptionReport() {
        return consumptionReport;
    }

    /**
     * Sets the value of the consumptionReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setConsumptionReport(DocumentReferenceType value) {
        this.consumptionReport = value;
    }

    /**
     * Gets the value of the logisticServiceReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logisticServiceReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogisticServiceReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogisticServiceReferenceType }
     * 
     * 
     */
    public List<LogisticServiceReferenceType> getLogisticServiceReference() {
        if (logisticServiceReference == null) {
            logisticServiceReference = new ArrayList<LogisticServiceReferenceType>();
        }
        return this.logisticServiceReference;
    }

    /**
     * Gets the value of the consignmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentReferenceType }
     *     
     */
    public ConsignmentReferenceType getConsignmentReference() {
        return consignmentReference;
    }

    /**
     * Sets the value of the consignmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentReferenceType }
     *     
     */
    public void setConsignmentReference(ConsignmentReferenceType value) {
        this.consignmentReference = value;
    }

    /**
     * Gets the value of the shipmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentReferenceType }
     *     
     */
    public ShipmentReferenceType getShipmentReference() {
        return shipmentReference;
    }

    /**
     * Sets the value of the shipmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentReferenceType }
     *     
     */
    public void setShipmentReference(ShipmentReferenceType value) {
        this.shipmentReference = value;
    }

    /**
     * Gets the value of the avpList property.
     * 
     * @return
     *     possible object is
     *     {@link EcomAttributeValuePairListType }
     *     
     */
    public EcomAttributeValuePairListType getAvpList() {
        return avpList;
    }

    /**
     * Sets the value of the avpList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EcomAttributeValuePairListType }
     *     
     */
    public void setAvpList(EcomAttributeValuePairListType value) {
        this.avpList = value;
    }

}
