ALTER TABLE C_DocTypeInfo ADD XX_DocTypeTNP_ID NUMBER(10);
ALTER TABLE C_DocTypeInfo ADD CONSTRAINT FK1006834_1036938X FOREIGN KEY (XX_DocTypeTNP_ID) REFERENCES C_DocType (C_DocType_ID);
ALTER TABLE C_DocTypeInfo ADD XX_IsTNPAuto CHAR(1) DEFAULT 'N' CHECK (XX_IsTNPAuto IN ('Y','N')) NOT NULL;
ALTER TABLE C_DocTypeInfo ADD XX_ChargeTNP_ID NUMBER(10);
ALTER TABLE C_DocTypeInfo ADD CONSTRAINT FK1006834_1036940X FOREIGN KEY (XX_ChargeTNP_ID) REFERENCES C_Charge (C_Charge_ID);
CREATE TABLE XX_TNPAUTO (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE DEFAULT SYSDATE NOT NULL, 
CreatedBy NUMBER(10) DEFAULT 0 NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, 
M_Inventory_ID NUMBER(10), M_Movement_ID NUMBER(10), Updated DATE DEFAULT SYSDATE NOT NULL, UpdatedBy NUMBER(10) DEFAULT 0 NOT NULL, 
XX_TNPAUTO_ID NUMBER(10) NOT NULL, CONSTRAINT PK1007587X PRIMARY KEY (XX_TNPAUTO_ID)); 
ALTER TABLE XX_TNPAUTO ADD CONSTRAINT FK1007587_1036941X FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client (AD_Client_ID);