CREATE  TABLE "AD_QUICKINFO" 
   (	"AD_CLIENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AD_ORG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AD_QUICKINFO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(255), 
	"ENTITYTYPE" VARCHAR2(6 BYTE) DEFAULT 'U' NOT NULL ENABLE, 
	"ISACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"NAME" NVARCHAR2(60) NOT NULL ENABLE, 
	"UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATEDBY" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	 CHECK (IsActive IN ('Y','N')) ENABLE, 
	 CONSTRAINT "PK2189" PRIMARY KEY ("AD_QUICKINFO_ID"), 
	 CONSTRAINT "FK2189_30493" FOREIGN KEY ("AD_CLIENT_ID")
	  REFERENCES "AD_CLIENT" ("AD_CLIENT_ID") ENABLE, 
	 CONSTRAINT "FK2189_30795" FOREIGN KEY ("ENTITYTYPE")
	  REFERENCES "AD_ENTITYTYPE" ("ENTITYTYPE") ENABLE, 
	 CONSTRAINT "FK2189_30494" FOREIGN KEY ("AD_ORG_ID")
	  REFERENCES "AD_ORG" ("AD_ORG_ID") ENABLE
   );