ALTER TABLE C_Order ADD DevisAmount NUMBER DEFAULT 35;
ALTER TABLE C_Order ADD Z_Devis_ID NUMBER(10); 
ALTER TABLE C_Order ADD CONSTRAINT FK259_1033515X FOREIGN KEY (Z_Devis_ID) REFERENCES C_Order (C_Order_ID);
CREATE INDEX Z_DEVIS_INDX ON C_ORDER (Z_DEVIS_ID);
