# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: 
#[push]

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build Smile
      run: mvn -B package --file pom.xml
    - name: Build Snaposhot
      run: mvn --file pom.xml --batch-mode --update-snapshots verify
    - run: mkdir downloads && cp /home/runner/work/compiere-eggo/compiere-eggo/compiere-jasper-eurocenter/target/*.jar downloads
    - run: cp /home/runner/work/compiere-eggo/compiere-eggo/compiere-custo-eurocenter/target/*.jar downloads
    - run: cp /home/runner/work/compiere-eggo/compiere-eggo/gwtServer-custo-eurocentertarget/*.jar downloads
    - run: cp /home/runner/work/compiere-eggo/compiere-eggo/fatjar-custo-eurocenter/*.jar downloads
    - run: cp /home/runner/work/compiere-eggo/compiere-eggo/fatjar-custo-eurocenter-ws/*.jar downloads
    - run: cp /home/runner/work/compiere-eggo/compiere-eggo/compiere-ws-eurocenter/*.jar downloads
    - uses: actions/upload-artifact@v2
      with:
        name: compiere-eggo
        path: staging/*
#compiere-custo-eurocenter
#compiere-jasper-eurocenter
#gwtServer-custo-eurocenter
#fatjar-custo-eurocenter
#compiere-ws-eurocenter

#fatjar-custo-eurocenter-ws

