--
-- script pour modification expiration mdp profile DEFAULT
--
SPOOL &1

ALTER PROFILE "DEFAULT" LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER SYSTEM SET OPEN_CURSORS = 5000 SCOPE = BOTH;
--ALTER SYSTEM SET SESSIONS = 500 SCOPE = BOTH;
--ALTER SYSTEM SET PROCESSES = 700 SCOPE = BOTH;


SPOOL OFF

EXIT