//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:18:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:gs1:ecom:ecom_common:xsd:3")
package gs1.ecom.ecom_common.xsd._3;
